### ISSUE TITLE
Dynamic code preview rendering for vue components

### ISSUE THREAD

**Issue by visini** [nuxt-modules/storybook#205]
Recently storybook added support for dynamic rendering of code preview for vue components.

See this pull request:
https://github.com/storybookjs/storybook/pull/12812

Instead of 

```js
(arg, { argTypes }) => ({
  components: { MyButton },
  props: Object.keys(argTypes),
  template: '<MyButton v-bind="$props" />',
})
```

... the code preview dynamically generates a code snippet (see example in pull request above). Example:

```vue
<template>
  <my-button rounded color="#f00">A Button with rounded edges</my-button>
</template>
```

See `@storybook/vue` demo: https://storybookjs.netlify.app/vue-kitchen-sink/?path=/docs/addon-controls--rounded (Storybook 6.1.11)

<img width="1023" alt="Screenshot 2020-12-17 at 18 01 23" src="https://user-images.githubusercontent.com/10230606/102518742-f6347280-4091-11eb-90d8-cb3e9778ce52.png">

Looking forward to support for this via `@nuxtjs/storybook`!

**Comment by visini** [comment]
As I suspected, it's a more complex issue than I thought, and not simply related to `@storybook/vue` version. 

Unfortunately I don't believe I'm the right person to take this on, my knowledge of Vue and Nuxt very limited and barely managed to track down the things that follow. I spent a few hours digging around in storybook docs vue source and manually tried to find which parts of the code is connected with this functionality.  Here's my investigation so far:

I cloned this repo and modified `playground/components/MyButton.stories.js`:

```js
import MyButton from "./MyButton";
export default {
  title: "Button",
  component: MyButton,
  argTypes: {
    rounded: { control: "boolean" },
  },
};

export const Template = (arg, { argTypes }) => ({
  components: { MyButton },
  props: Object.keys(argTypes),
  template: '<MyButton v-bind="$props">123</MyButton>',
});

export const Primary = Template.bind({});
Primary.args = {
  label: "Primary",
  rounded: true,
};
```

Then, I investigated within sourceDecorator.js from storybook docs addon vue code – I saw console errors from this specific file: 

See this specific file and code segment (error occurred in last line of highlighted portion):
https://github.com/storybookjs/storybook/blob/b747c5c2396786682f36e5ac9b78ea990b6f952d/addons/docs/src/frameworks/vue/sourceDecorator.ts#L50-L56

Related error: `Failed to generate dynamic story source: TypeError: null is not an object (evaluating 'storyNode._vnode')
sourceDecorator — sourceDecorator.js:136`

After I comment out dynamic story instance identification via vm, and manually use window.$nuxt..., it seems to be a step in the right direction. See here:

```js
    var channel = _addons.addons.getChannel();
    // var storyComponent = getStoryComponent(story.options.STORYBOOK_WRAPS);
    // console.log("storyComponent", storyComponent())
    // var storyNode = lookupStoryInstance(vm, storyComponent);
    // console.log("storyNode", storyNode)
    var code = vnodeToString(window.$nuxt.$children[0].$children[0].$children[0].$vnode);
    console.log("code",  code)
```

In the console, I can see the logs of component stories being formatted with each change of args (e.g., toggle "rounded" via the toggle button in docs):

```bash
sourceDecorator.js:142:

code <MyButton rounded label="Primary">123</MyButton>
```

Initially, the formatted code displayed below the story stays the same:

<img width="1033" alt="Screenshot 2020-12-17 at 21 20 07" src="https://user-images.githubusercontent.com/10230606/102541650-f55f0900-40b0-11eb-8b1e-9af8f5961ad5.png">

But then, after I change args a few times (e.g., toggle "rounded" via the toggle button in docs) _twice_, the formatted code is updated accordingly:  

<img width="1049" alt="Screenshot 2020-12-17 at 21 20 12" src="https://user-images.githubusercontent.com/10230606/102541762-1889b880-40b1-11eb-8e56-14e425fde579.png">

Now, obviously these are nothing more than a few leads, but I'm afraid that I feel out of my depth. I'll be following this issue and am ready to reproduce or confirm any behavior, though.

Many thanks!

**Comment by farnabaz** [comment]
Awesome work @visini, Thanks for the issue and investigation. This is definitely is a tough issue to solve. Unfortunately storybook does not have proper way to customize internals.   
This might be solve by modifying modules internals without need to change `sourceDecorator`.  If not we should write our own `sourceDecorator` with same logic you explained.

**Comment by aacassandra** [comment]
Hello @farnabaz @Atinux  , does the current storybook / nuxtjs support as suggested by @visini .

**Comment by aacassandra** [comment]
hmm .. for a while I used the original storybook package and it worked. i hope it works on nuxt/storybook soon. thankyou friends

**Comment by pocka** [comment]
Starting from storybook@v6.2.0-beta.2, the `sourceDecorator` reuses an existing Vue node tree instead of `new Vue`-ing. Could you try it?

https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.2

**Comment by philwolstenholme** [comment]
https://github.com/storybookjs/storybook/pull/14002 is the PR for the change @pocka mentioned

**Comment by philwolstenholme** [comment]
@farnabaz I wonder if the release of 6.2 will help us with this issue 🤔

**Comment by farnabaz** [comment]
In order to get it worked you need to define first argument for all your stories. This way storybook detects that your story depends on arguments and renders the code. @philwolstenholme 

```js
const SampleComponent = (args) => '<div>With Source</div>`
```

**Comment by philwolstenholme** [comment]
Hi @farnabaz , I don't quite understand?

This is an example story of mine:

```
import * as components from '~/.nuxt-storybook/components';

export default {
  title: 'atoms/Button',
  component: components.AtomsVaButton,
  argTypes: {
    iconPosition: {
      control: {
        type: 'select',
        options: ['left', 'right'],
      },
    },
  },
  args: {
    slotContent: 'Button slot content',
  },
};

const Template = (arg, { argTypes }) => ({
  props: Object.keys(argTypes),
  template: `<atoms-va-button v-bind="$props">{{ slotContent }}</atoms-va-button>`,
});

export const Default = Template.bind({});
Default.storyName = 'VaButton';

export const WithIcon = Template.bind({});
WithIcon.storyName = 'With icon';
WithIcon.args = {
  iconName: 'va/right-arrow',
};

export const WithIconOnRight = Template.bind({});
WithIconOnRight.storyName = 'With icon on right';
WithIconOnRight.args = {
  iconName: 'va/left-arrow',
  iconPosition: 'right',
};
```
and this is what appears in the Docs tab preview:

Note the missing component visual preview:

![A Docs tab in Storybook with no visual preview of the component and showing Storybook specific code rather than the component code](https://user-images.githubusercontent.com/6339853/113907593-76abea00-97cd-11eb-8eb4-9f51d8839621.png)

And the code:

```
(arg, { argTypes }) => ({
  props: Object.keys(argTypes),
  template: `<atoms-va-button v-bind="$props">{{ slotContent }}</atoms-va-button>`,
})
```

**Comment by webzlodimir** [comment]
Have same issue with code preview

**Comment by farnabaz** [comment]
Try using `Template` without bind. @philwolstenholme 
```js
export const Default = Template;
```

**Comment by philwolstenholme** [comment]
Hmmm so if I try

```
const Template = (arg, { argTypes }) => ({
  props: Object.keys(argTypes),
  template: `<atoms-va-button v-bind="$props">{{ slotContent }}</atoms-va-button>`,
});

export const Default = Template;
Default.storyName = 'VaButton';
```

Then I get no preview in the Docs tab, and Storybook says no code is available either. The Canvas tab still works though:

![Screenshot 2021-04-15 at 11 42 45](https://user-images.githubusercontent.com/6339853/114857042-bbdca700-9ddf-11eb-9cf0-631eaf19b7cf.png)
![Screenshot 2021-04-15 at 11 41 55](https://user-images.githubusercontent.com/6339853/114857044-bc753d80-9ddf-11eb-8b8b-6daddebb618a.png)

**Comment by webzlodimir** [comment]
Conducted an experiment and found out the following.

I try:

```
import BaseButton from '@/components/base/BaseButton'

export default {
  title: 'Base/Buttons',
  component: BaseButton,
}

export const DefaultButton = (args) => ({
  components: { BaseButton },
  template: '<base-button>Кнопка</base-button>',
})
```

On docs page i see:

![image](https://user-images.githubusercontent.com/31979423/114860455-b047ab00-9df4-11eb-9d86-0fcd300b57da.png)

But, if i click on "Refresh controls" button, i see:

![image](https://user-images.githubusercontent.com/31979423/114860596-e08f4980-9df4-11eb-95d4-c49c8982556b.png)

**Comment by Rigo-m** [comment]
I have the same problem as @philwolstenholme .

Why are you guys suggesting to not use `Template.bind({})` anymore? This goes against writing DRY code :/ How would we tackle many stories of a component? Should we write a new template function every time?

**Comment by webzlodimir** [comment]
Any update of this issue guys?

**Comment by schristian30** [comment]
I also have the same issue, any update on how to fix it guys?

**Comment by Decipher** [comment]
While this is not a final solution, I have been working around this issue by providing a source parameter:

```
Default.parameters = {
  docs: {
    source: {
      code: '<MyComponent />
    }
  }
}
```

**Comment by webzlodimir** [comment]
> While this is not a final solution, I have been working around this issue by providing a source parameter:
> 
> ```
> Default.parameters = {
>   docs: {
>     source: {
>       code: '<MyComponent />
>     }
>   }
> }
> ```

It will be legen "wait-wait" dary, legendary!

**Comment by schristian30** [comment]
> While this is not a final solution, I have been working around this issue by providing a source parameter:
> 
> ```
> Default.parameters = {
>   docs: {
>     source: {
>       code: '<MyComponent />
>     }
>   }
> }
> ```

Still not fixed mine, for me it just show "<MyComponent />" as code

**Comment by Decipher** [comment]
@schristian30 Is your story exported as `Default`? This is just an example, for the correct documentation please refer to https://storybook.js.org/docs/vue/writing-docs/doc-blocks#docspage-1

**Comment by mrillusion** [comment]
For anyone looking at this and using [@nuxtjs/storybook](https://github.com/nuxt-community/storybook) updating the  @nuxtjs/storybook package to 4.3.1 resolved the issue for me.

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
