### ISSUE TITLE
[Storyshots] Error: No script available to transform

### ISSUE THREAD

**Issue by EdisonHarada** [nuxt-modules/storybook#215]
Hello,

I'm having the following error trying to setup @storybook/addon-storyshots to an existent nuxt project: 
![image](https://user-images.githubusercontent.com/5961396/105104307-4a2be000-5ab2-11eb-91e8-8ab6d6f0bbad.png)

So I created a brand new nuxt project with Tailwind and Jest, and I installed nuxt-storybook + @storybook/addon-storyshots (here: https://github.com/EdisonHarada/nuxt-storyshots), and I still get the same issue.
![image](https://user-images.githubusercontent.com/5961396/105104333-52841b00-5ab2-11eb-8a95-f7855bd5137a.png)

The command "npx nuxt storybook" works fine and shows the story, but when I try to run jest I get the error.

I also debugged the code and I find out where it's throwing the error. The file is: node_modules\@storybook\addon-storyshots\dist\frameworks\configure.js, line 75:
![image](https://user-images.githubusercontent.com/5961396/105104477-9e36c480-5ab2-11eb-8532-6f682541be8b.png)
Apparently, when the method "jest.requireActual(preview)" is called with the preview.js file it throws the error message "No script available to transform".

I also tested that if I remove the file preview.js the storyshots works, but I need the preview.js file.
![image](https://user-images.githubusercontent.com/5961396/105104630-ec4bc800-5ab2-11eb-872c-20fc16175bad.png)

Does anyone know if I'm missing some configuration or there's something wrong with storybook?

**Comment by simondib** [comment]
@EdisonHarada I checked out your repo but am getting: 

> $ Mon Mar 29 18:48:23 ~/repos/nuxt-storyshots-main > jest
 PASS  test/Logo.spec.js
 FAIL  test/storybook.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, lstat '/repos/nuxt-storyshots-main/.storybook'

      2 | import initStoryshots from '@storybook/addon-storyshots'
      3 |
    > 4 | initStoryshots({ configPath: path.resolve(__dirname, '../.storybook') })

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
