### ISSUE TITLE
Please create a codesandbox.io for nuxt storybook

### ISSUE THREAD

**Issue by travis5491811** [nuxt-modules/storybook#249]
### Is your feature request related to a problem? Please describe.
I tried to follow the issue request of `fork of https://codesandbox.io/s/nuxtjsstorybook-demo-l164h`. It says storybook in the url but that fork is not a nuxt storybook fork, it's a nuxt content example.

### Describe the solution you'd like
A nuxt storybook example to fork from codesandbox.io to help show issue when creating an issue or bug. Update the link in the issue template to be the nuxt storybook example.

### Describe alternatives you've considered
Create more github repos to show issue.

### Additional context
I tried to follow the issue request of `fork of https://codesandbox.io/s/nuxtjsstorybook-demo-l164h`. It says storybook in the url but that fork is not a storybook fork, it's a nuxt content example. I tried to add the necessary dependencies to make it a storybook example by looking at what was in my project. The result was many errors and never being able to actually get `nuxt` storybook working in `codesandbox.io`.  I also did a web search trying to find a codesandbox template for `nuxt` storybook and found https://codesandbox.io/s/k4zim?file=/pages/index.vue but without changing anything, that project just returns 502 bad gateway in the sandbox browser and the console says ...started

**Comment by beazergood** [comment]
I too am experiencing this. I'm trying to create a repro of a different issue I'm having and cannot even get storybook installed into my nuxt sandbox without loads of errors.

**Comment by travis5491811** [comment]
I'm not sure if this is a work in progress or not but the following are also broken https://storybook.nuxtjs.org/examples/manual/ and https://codesandbox.io/s/github/nuxt-community/storybook/tree/master/examples/manual-setup?from-embed

**Comment by jeanniesarah** [comment]
any updates on this?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
