### ISSUE TITLE
Tailwind classes not working when changed in actions

### ISSUE THREAD

**Issue by lopermo** [nuxt-modules/storybook#251]
### Version
@nuxtjs/storybook: 3.3.1
nuxt: 2.14.12

### Reproduction Link
The sandbox provided in the example doesn't work.
https://codesandbox.io/s/github/nuxt-community/storybook/tree/master/examples/tailwind

### What is actually happening?
Copy the same config as in the sandbox and everything works alright, but when I set up a story with tailwind classes and it works alright, it's displayed with the right styles in the canvas; but when I modify the classes through actions, it will only work if I set the default ones. e.g: it'll only load the tailwind classes that come as "default" from the component (text-orange-700 as default will work, but change it through actions to text-orange-800 and it won't work, change it back to text-orange-700 and it works again).

### Code
```javascript
<template>
  <div :class="['px-6 py-2 font-medium rounded-lg w-max', styles]">
    <slot>{{ text }}</slot>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: "Placeholder",
    },
    styles: {
      type: String,
      default: "bg-yellow-100 text-yellow-600",
    },
  },
};
</script>
```

```javascript
import MyBadge from './Badge'
export default {
  title: 'Badge',
  component: MyBadge,
  argTypes: {
    styles: { control: 'text' },
    text: {
      control: 'text',
      defaultValue: 'Placeholder'
    }
  }
}

export const Badge = (arg, { argTypes }) => ({
  components: { MyBadge },
  props: Object.keys(argTypes),
  template: '<Badge v-bind="$props" />'
})
```

**Comment by philwolstenholme** [comment]
Are you purging your Tailwind classes? If you add the `text-orange-800` class via your browser's devtools rather than Storybook does the text colour change?

**Comment by lopermo** [comment]
> Are you purging your Tailwind classes? If you add the `text-orange-800` class via your browser's devtools rather than Storybook does the text colour change?

this is my tailwind config:
As you can see, I tried with only purging in production, and then I commented the whole thing, still nothing. I did what you suggested and nothing changes. I can't find the classes anywhere in the devtools

```javascript
module.exports = {
  // purge: {
  //   enabled: process.env.NODE_ENV === 'production',
  //   content: [
  //     'components/**/*.vue',
  //     'layouts/**/*.vue',
  //     'pages/**/*.vue',
  //     'plugins/**/*.js',
  //     'nuxt.config.js',
  //   ]
  // },
  theme: {
    extend: {
      colors: {
        "ghost": "#f9f9fe",
        header: {
          "light": '#423f76',
          DEFAULT: "#110f52"
        }
      },
      fontFamily: {
        sans: ['JakartaSans', 'sans-serif'],
        body: ['JakartaSans', 'sans-serif']
      }
    }
  },
  variants: {
    translate: ({ after }) => after(['group-hover'])
  }
}
```

**Comment by philwolstenholme** [comment]
If adding the class via devtools isn't working then I think it means Tailwind hasn't generated a class with that name.

It sounds like this isn't a Nuxt or Storybook issue but maybe an issue with your Tailwind config? Since commenting out the purging have you restarted the Postcard/Tailwind CLI command e.g. by closing your terminal session or window? I wonder if Tailwind is still purging? 🤔

**Comment by lopermo** [comment]
Yup, did all that.
This is my nuxt config, just in case you see something I'm missing:
```javascript
build: {
    extractCSS: true,
    filenames: {
      app: ({ isDev }) => (isDev ? '[name].js' : '[contenthash].js'),
      chunk: ({ isDev }) => (isDev ? '[name].js' : '[contenthash].js'),
      css: ({ isDev }) => (isDev ? '[name].css' : '[contenthash].css'),
      img: ({ isDev }) =>
        isDev ? '[path][name].[ext]' : 'img/[contenthash:7].[ext]',
      font: ({ isDev }) =>
        isDev ? '[path][name].[ext]' : 'fonts/[contenthash:7].[ext]',
      video: ({ isDev }) =>
        isDev ? '[path][name].[ext]' : 'videos/[contenthash:7].[ext]'
    },
    transpile: [],
    extend(config, ctx) {
      config.module.rules.push({
        test: /\.vue$/,
        loader: 'vue-svg-inline-loader',
        options: {}
      })
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push(
          {
            test: /\.vue$/,
            loader: "vue-svg-inline-loader",
            options: {},
          }
        );
      }
      config.resolve.alias.vue = "vue/dist/vue.common";
    },
    postcss: {
      preset: {
        autoprefixer: {
          add: true,
          grid: false
        }
      }
    }
  },
```

**Comment by lopermo** [comment]
I pushed to a public repository so that you can see what I mean:
https://github.com/lopermo/newlopermo.com/tree/storybook

**Comment by Rigo-m** [comment]
You need to enable purge and use it to read class names from components and stories.

**Comment by AugustBurnsRed** [comment]
@lopermo 

Hi, i had the same problem. I wanted to add custom class in tailwind.config.js. They were being loaded in the Nuxt side of the app but not in Storybook.

To fix it, i used the custom config like this: https://storybook.nuxtjs.org/advanced/manual-setup. After in my .storybook/main.js, in webpackFinal

`config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              plugins: [require('tailwindcss'), require('autoprefixer')],
            },
          },
        },
      ],
      include: path.resolve(__dirname, '../'),
    })`

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
