### ISSUE TITLE
Path resolution error when generating static build

### ISSUE THREAD

**Issue by simondib** [nuxt-modules/storybook#288]
Getting a path resolution error on `yarn build-storybook`. 

Manually editing `.nuxt-storybook/storybook/preview.js` to an absolute path resolves, but this generates a different error, and this isn't a workable solution in any case as this file is auto-generated.

### Version
@nuxtjs/storybook: 4.0.4
nuxt: 2.15.3

### Reproduction Link
https://codesandbox.io/s/inspiring-voice-1wxv2

### Steps to reproduce
1. Open Codesandbox project
2. run `yarn storybook:build` and observe error

### What is Expected?
Storybook static build to generate successfully.

### What is actually happening?
```ERR! Module not found: Error: Can't resolve '~~/.nuxt-storybook/storybook/preview.js' in '/sandbox/.storybook'```

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
