### ISSUE TITLE
Support for Vite

### ISSUE THREAD

**Issue by arpadgabor** [nuxt-modules/storybook#289]
### Context
Storybook 6.3 introduced Vite as a build tool. It would be great if support for this was added.

https://storybook.js.org/blog/storybook-for-vite/

**Comment by tobiasdiez** [comment]
The instructions outlined at https://github.com/nuxt-community/storybook/pull/385 worked for me (for nuxt3, but I think something similar should also work for nuxt2 + bridge + vite). Feedback welcome!

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
