### ISSUE TITLE
Can't build directly into `static` dir

### ISSUE THREAD

**Issue by hacknug** [nuxt-modules/storybook#295]
### Version
@nuxtjs/storybook: v4.0.4
nuxt: v2.15.7

### Reproduction Link
https://codesandbox.io/s/confident-leavitt-65nxb

### Steps to reproduce
I've added a couple scripts to illustrate my issue. 
- `storybook:build-works` shows how you can build Storybook using the defaults and there's no issues.
- `storybook:build-breaks` shows how if you try to build Storybook into the `/static` dir, the module will recursively copy the contents of the folder inside itself until the OS prevents from creating things in that dir.

### What is Expected?
I would expect the module to remove the previous build dir (it already does this). Then if the user has specified a custom `--output-dir`, the module should check if that path is inside `--static-dir`. 

If it is not inside `--static-dir`, I think everything works fine. If it is inside, the module should copy the contents of the static folder except for the folder that will be our `--output-dir`.

### What is actually happening?

Because I'm trying to deploy my Storybook with my website, when the module copies my static files to the Storybook build dir, it also copies Storybook's dir. This causes said dir to be infinitely nested/duplicated.

I think this is causing my CodeSandbox example to not demo the issue properly. Try running it locally if it's still not clear what's going on. Find attached a screenshot showing how my `static` dir looks like after a build.

<details><summary>screenshot</summary>
<img width="497" alt="Captura de pantalla 2021-06-30 a las 17 27 02" src="https://user-images.githubusercontent.com/1107521/123988756-90be2880-d9c8-11eb-8277-69f0b78f1ace.png"></details>

**Comment by hacknug** [comment]
For anyone trying to deploy their storybook dir with their website, this script allows you to workaround the described issue:

```bash
rm -r -f static/storybook && nuxt storybook build && mv storybook-static static/storybook
```

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
