### ISSUE TITLE
Vuex in Storybook

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt-modules/storybook#313]
How do I expose/use the Vuex modules defined in `/store` in Storybook?

**Comment by existe-deja** [comment]
Your store is already loaded by defaut. If you download the beta version of the devtool browser extension you can explore it.

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
