### ISSUE TITLE
Problem create a custom theme

### ISSUE THREAD

**Issue by Suv4o** [nuxt-modules/storybook#314]
Does anyone know how can we create a theme? According to the official Storybook Docs, we need to create a file in ".storybook/manager.js", in our case I assume is ".nuxt-storybook/storybook/manager.js". But this doesn't work. 

Also I tried to run `npx nuxt storybook eject`. But no luck there either.

Any thoughts?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
