### ISSUE TITLE
Integration with @nuxtjs/svg

### ISSUE THREAD

**Issue by pepeloper** [nuxt-modules/storybook#316]
is it possible to make it work with the [SVG Module](https://github.com/nuxt-community/svg-module) ?

If I import a svg in a component I get the following error: 

`Module not found: Error: Can't resolve '@/assets/design-system/error.svg?inline' in '/Users/pepeloper/my-project/components/design-system/form'`

Thanks!

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
