### ISSUE TITLE
Problem Creating A Custom Args

### ISSUE THREAD

**Issue by farahali98** [nuxt-modules/storybook#319]
I'm facing a problem creating a **custom argument.** I want to create content arg as a **quill editor** but didn't find anything helpful with that. Instead of having the content input like that I want to have a **quill editor in the control below**. Any idea?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
