### ISSUE TITLE
Vuetify theme options - hot reload not updating 

### ISSUE THREAD

**Issue by IOIIOOIO** [nuxt-modules/storybook#324]
### Version
@nuxtjs/storybook: v4.1.1
@nuxtjs/vuetify": v1.12.1
nuxt: v2.15.7

### Steps to reproduce
Setup Nuxt with the following CLI options:
UI Framework: Vuetify.js
Rendering mode: SPA
Server: Node.js

Install @nuxt/storybook. 

Run `nuxt storybook`

Update theme colors in `nuxt.config.js`

```
vuetify: {
    themes: {
            light: {
              primary: colors.amber.darken2,
             }
    }
}
```

### What is Expected?
The colors should be updated in Storybook.

### What is actually happening?
It only works the first time, any subsequent changes require rebuilding by ending the task and running `nuxt storybook` to build from scratch again. 

### Further information:
I have looked inside the compiled directory `.nuxt-storybook/vuetify/options.js` and the theme has been updated correctly.
If I look in my browser `network` tab - the second time I change a theme option it doesn't update with a new call to `[code].hot-update.json`.

**Comment by tim-kilian** [comment]
I have kind of the same issue. For me every plugin just work on the initial build, when then changing some CSS the component start to rerender and throw an error, that the plugin is not loaded.

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
