### ISSUE TITLE
Relative stories paths should match nuxt config location

### ISSUE THREAD

**Issue by hypervillain** [nuxt-modules/storybook#328]
#### Problem
At the moment, relative stories paths (eg. `./`) are inserted as-is into `.nuxt-storybook/storybook/main.js`, resulting in an invalid path for Storybook and breaking it immediately.

#### I would like
To rewrite the relative paths before inserting them inside Storybook main configuration.

#### Additional context
In our case, prefixing paths with `~/` is not a viable solution: we automatically write the stories paths for our users, without knowing the context in which Storybook is run.

Happy to discuss this and create a PR.
Thanks!

**Comment by phillysnow** [comment]
linked issue in the forum: https://community.prismic.io/t/slicemahine-latest-update-breaking-nuxt/7287/4

**Comment by farnabaz** [comment]
Hey sorry for the late response
What is the base directory for relative pathes? Does `./` refers to project root?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
