### ISSUE TITLE
nuxt bridge / nitro / Storybook: TypeError: Router.use() requires a middleware function but got a undefined

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/storybook#350]
# Problem
`serverMiddleware` specified with `path` and `handler`, e.g. `{ path: '/healthcheck', handler: '~/api/healthcheck.ts' }` can break existing software like `nuxt-storybook` because [nitro's middleware functionality](https://github.com/nuxt/framework/blob/d68318f9d5ee25f6377edb866cd1b5846e8bfdce/packages/nitro/src/server/middleware.ts#L83) removes all object properties but not the object itself from Nuxt's `serverMiddleware` options. Other tools might get confused by an empty object and fail to start. Internally, nitro goes on using  middleware objects extracted from Nuxt's options and does not care about the "destroyed" object.

# A solution
One easy fix is to just use the new [server directory structure](https://v3.nuxtjs.org/docs/directory-structure/server/). Put your api files under `~/server/api` and your server middlewares under `~/server/middleware`, removing the `serverMiddleware` property from `nuxt.config.ts` and you should be good to go!

I'll leave this issue open for now in case somebody wants to change the deletion logic. If done or not, feel free to close and have this as a pointer for future users to come!

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
