### ISSUE TITLE
Action logging for programmatic navigation 

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/storybook#352]
### Is your feature request related to a problem? Please describe.
When I click a nuxt-link I get a nice logging inside the action panel but nothing for programmatic navigation

### Describe the solution you'd like
I would have the same logging if I trigger a programmatic navigation 

### Describe alternatives you've considered
Maybe a global navigation guard can do the trick?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
