### ISSUE TITLE
Codesandbox example for MDX is broken

### ISSUE THREAD

**Issue by yannbf** [nuxt-modules/storybook#392]
When accessing the page https://storybook.nuxtjs.org/examples/mdx I noticed that the example is broken:
![image](https://user-images.githubusercontent.com/1671563/168554232-9a2af1b0-d38c-4e2c-83ca-262201527249.png)

When opening the codesandbox embed, this is the issue:
![image](https://user-images.githubusercontent.com/1671563/168553982-614eea04-e7f4-401d-bfa1-cc16b0f4d416.png)

### Version
@nuxtjs/storybook: 
nuxt: 

### Reproduction Link

https://codesandbox.io/s/github/nuxt-community/storybook/tree/master/examples/mdx?from-embed

### Steps to reproduce

Just open the link

### What is Expected?

The example should work 

### What is actually happening?

Might be related to an internal dependency of the project. Maybe recreating a sandbox will fix it, or just upgrading some libraries.

**Comment by jonathanmach** [comment]
+1 I'm facing the same issue.

Hey @yannbf, quick question: did you manage to get MDX to work?
I'm getting a blank page and this error on the console: https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
