### ISSUE TITLE
An error message is displayed `applyDecorators was not supported :( !` in console.

### ISSUE THREAD

**Issue by SugiShio** [nuxt-modules/storybook#398]
### Version
@nuxtjs/storybook: v4.3.2
nuxt: v2.15.8

### Steps to reproduce
Install the version and launch storybook

### What is actually happening?
An error message is displayed `applyDecorators was not supported :( !` in console.

### What is Expected?
The message is not shown up.

**Comment by ProjektGopher** [comment]
I'm also seeing this issue, but I don't think it's to do with @nuxtjs/storybook as I don't have that as a dependency. I haven't been able to figure out where this is being console logged.

**Comment by tomleo** [comment]
I've run into this same issue, and cannot figure out the origin.

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
