### ISSUE TITLE
Components not visible in docs tab if using parameters in preview.js (ejected manual config)

### ISSUE THREAD

**Issue by chesterlaykin** [nuxt-modules/storybook#406]
### Version
@nuxtjs/storybook: 4.3.2
nuxt: 2.15.8

### Reproduction Link
https://stackblitz.com/edit/github-cduzne

### Steps to reproduce
After doing `yarn nuxt storybook eject`, add parameters object to` preview.js:`

`export const parameters = {};`

### What is Expected?
Components should still be visible in docs tab

### What is actually happening?
Components are not visible in docs tab

If I add parameters to preview.js, the components disappear in the docs tab.
I found a way to make them appear basd on this issue [375](https://github.com/nuxt-community/storybook/issues/375)
So it seems that I have to import the parameters and declare them inside a "docs" object.
```
import {
  parameters as nuxtParameters
} from "~~/.nuxt-storybook/storybook/preview.js";

export const parameters = {
  docs: {
      ...nuxtParameters.docs
  }
}
```
That info isn't in the docs though. Or else it's a bug, unless I have missed something?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
