### ISSUE TITLE
Support HTTPS for local dev server

### ISSUE THREAD

**Issue by Exotelis** [nuxt-modules/storybook#412]
It seems that the https parameter is not supported by nuxt storybook, as it is for storybook. This might not be a bug but a feature request. Have you thought about supporting this for nuxt storybook also?

### Version
@nuxtjs/storybook: v4.3.2
nuxt: 2.15.8

### Steps to reproduce
On the cli just run:
```
nuxt storybook --https
```

### What is Expected?
I would expect the dev server to start with https, as storybook would do it also. Please see the [storybook docs](https://storybook.js.org/docs/react/api/cli-options)

### What is actually happening?
It fails to start the server

**Comment by daguitosama** [comment]
In the best use the best tool for the job spirit, you could offload TLS stuff to a more in the weeds server like [Caddy](https://caddyserver.com) , it has https support out of the box, even on localhost, easy to config as a reverse proxy to pair with the Nuxt server.

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
