### ISSUE TITLE
How to add documentation associated with my component ?

### ISSUE THREAD

**Issue by Kamsou** [nuxt-modules/storybook#413]
Hello guys, 

Projet 		`"nuxt-edge": "^2.16.0-27358576.777a4b7f",`

I have a `pagination.stories.js` file in my project and I try to add some documentation in the "Docs" tab, 
but when I install the `@storybook/addon-docs` lib the tab disappears. I tried to create an additional mdx file with my markdown doc in `pagination.stories.mdx` but nothing happens. Any ideas?

![Capture d’écran 2023-01-02 à 15 26 51](https://user-images.githubusercontent.com/41164034/210244489-5b1b5087-e0c2-441e-b332-45547f7d2b02.png)

`pagination.stories.js`

```
import LtPagination from '@/components/LtPagination/index.vue'

export default {
    title: 'Components/Pagination',
    component: LtPagination,
    argTypes: {},
}

const Template = (args) => ({
    components: {
        LtPagination,
    },
    setup: () => ({ args }),
    template: `<LtPagination v-bind="args" />`,
})

export const Default = Template.bind({})
Default.args = {
    totalItems: 200,
    itemsPerPage: 20,
    maxVisiblePages: 3,
}

export const Medium = Template.bind({})
Medium.args = {
    totalItems: 15000,
    itemsPerPage: 20,
    maxVisiblePages: 3,
}

export const Maximum = Template.bind({})
Maximum.args = {
    totalItems: 500000,
    itemsPerPage: 20,
    maxVisiblePages: 3,
}

```

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
