### ISSUE TITLE
Make @storybook-vue/nuxt a dependency

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-modules/storybook#431]
As far as I understand, one also has to have @storybook-vue/nuxt installed. This is neither a dependency nor is it mentioned in the docs. Also I think the storybook cli needs to be installed separately.

**Comment by chakAs3** [comment]
Please check this blog post, let me know what you think we can do to improve this and docs https://medium.com/@flashchakir/unleash-your-creativity-with-the-new-storybook-nuxt-module-b7beb1441bed

**Comment by tobiasdiez** [comment]
I would say add your storybook addon as a real dependency of the nuxt module, and the storybook cli maybe as a peer dependency?

**Comment by chakAs3** [comment]
> I would say add your storybook addon as a real dependency of the nuxt module, and the storybook cli maybe as a peer dependency?

i see your idea but my object is to be able to remove the module package, and you still can run your storybook
the module meant to connect your storybook app inside pour Nuxt app as a part of devtools.

**Comment by chakAs3** [comment]
> > I would say add your storybook addon as a real dependency of the nuxt module, and the storybook cli maybe as a peer dependency?
> 
> i see your idea but my object is to be able to remove the module package, and you still can run your storybook the module meant to connect your storybook app inside pour Nuxt app as a part of devtools.

still adding storybook-vue/nuxt as direct dependency may look natural,  but if you just npx storybook-nuxt init will add 
- module and preset to your package.json
- generate storybook config file.

there is no dependency between the module and preset framework.

**Comment by tobiasdiez** [comment]
> > I would say add your storybook addon as a real dependency of the nuxt module, and the storybook cli maybe as a peer dependency?
> 
> i see your idea but my object is to be able to remove the module package, and you still can run your storybook the module meant to connect your storybook app inside pour Nuxt app as a part of devtools.

This would still work, with the only minor annoyance that one has to install `storybook-vue/nuxt` again manually. But I think this is okay, this use case shouldn't happen often. But yeah, if in your opinion this is a must-have, then I suggest adding `storybook-vue/nuxt` as a peer-dependency.

**Comment by chakAs3** [comment]
yes adding storybook-vue/nuxt as peer-dependency may be a good idea, 
 `npx storybook-nuxt init` would install the module. 
 `npx storybook-nuxt init --enable-module` would install the module and enable it for you

**Comment by tobiasdiez** [comment]
Done now.
