### ISSUE TITLE
Default setup is not working

### ISSUE THREAD

**Issue by maciej-jezierski** [nuxt-modules/storybook#441]
Default setup in module description is not working with pnpm and monorepo. It doesn't install additional packages.
When you try to install them manually per output it doesn't read the stories. 

Project is set up correctly only if `npx storybook-nuxt init` is executed.  The reason behind it are probably devDependencies. This command is also modifying package.json scripts which are not mentioned in setup. As I want to keep storybook separate from library it's preferable way.

`  15 |   "devDependencies": {
  16 |     "@nuxt/devtools": "latest",
- 17 |     "@nuxtjs/storybook": "^7.0.0",
- 18 |     "@storybook-vue/nuxt": "^0.1.7",
- 19 |     "@storybook/addon-essentials": "^7.4.6",
- 20 |     "@storybook/addon-interactions": "^7.4.6",
- 21 |     "@storybook/addon-links": "^7.4.6",
- 22 |     "@storybook/vue3": "^7.4.6",
+    |     "@nuxtjs/storybook": "7.0.0",
+    |     "@storybook-vue/nuxt": "0.1.7",
+    |     "@storybook/addon-essentials": "7.5.0-alpha.3",
+    |     "@storybook/addon-interactions": "7.5.0-alpha.3",
+    |     "@storybook/addon-links": "7.5.0-alpha.3",
+    |     "@storybook/vue3": "7.5.0-alpha.3",
  23 |     "@storybook/vue3-vite": "^7.4.6",
  24 |     "nuxt": "^3.7.4",
- 25 |     "storybook": "^7.4.6",
+    |     "storybook": "7.5.0-alpha.3",
  26 |     "vue": "^3.3.4",
- 27 |     "vue-router": "^4.2.5"
+    |     "vue-router": "^4.2.5",
+    |     "react": "^18.2.0",
+    |     "react-dom": "^18.2.0",
+    |     "@types/node": "^18.17.5",
+    |     "@storybook/builder-vite": "7.5.0-alpha.3",
+    |     "@storybook/testing-library": "^0.2.0",
+    |     "@storybook/blocks": "7.5.0-alpha.3"
  28 |   }
`
![Screenshot 2023-10-05 at 11 54 06](https://github.com/nuxt-modules/storybook/assets/25454744/f4845fa6-28c0-413e-b4fc-4ebf91c5d649)

**Comment by damevin** [comment]
That's worked on my side, have you a reproduction ?

**Comment by tobiasdiez** [comment]
We have improved the situation around dependencies in the last few releases. This should have taken care of this issue, if not please comment and I'll reopen it.
