### ISSUE TITLE
4.3.2: Super slow compile times (over 10 seconds) with only 1 component

### ISSUE THREAD

**Issue by melvinprindustry** [nuxt-modules/storybook#445]
I know, I know, we should upgrade to Next 3 and use the latest of this package. However, we do not have that luxury right now. However, we still would like to implement Storybook (or at least, I would!). Though right now with my current setup with Nuxt 2.17.1 on Nitro with @nuxt/bridge the compilation time per file change is over 10 seconds long.

Do you have any recommendations in how to improve the speed of storybook (or nuxt in general?). Thanks!

**Comment by tobiasdiez** [comment]
The version compatible with nuxt v2 is no longer actively maintained. We accept PRs but will not work on it ourselves. Sorry for the inconvenience.
