### ISSUE TITLE
global registration of components and use of pathPrefix: false throws an error

### ISSUE THREAD

**Issue by iboargun** [nuxt-modules/storybook#448]
If i want to use global components in nuxt.config.ts because of dynamic rendering of components i receive an error:

`components: [
    {
      path: '~/components',
      global: true,
      pathPrefix: false,
    }
  ]
`

The error that appears is:
```
The symbol "_hoisted_1" has already been declared
 import { toDisplayString as _toDisplayString, createElementVNode as _createElementVNode, resolveComponent as _resolveComponent, createVNode as _createVNode, normalizeClass as _normalizeClass, openBlock as _openBlock, createElementBlock as _createElementBlock, createCommentVNode as _createCommentVNode } from "vue"
```

**Comment by Slimpak** [comment]
I've also encountered this issue. As a temporary workaround, I've switched the framework from **@storybook-vue/nuxt** to **@storybook/vue3-vite** until the problem is resolved.

**Comment by tdekoning** [comment]
Having the same problem here

**Comment by tobiasdiez** [comment]
Global components should now work with https://github.com/nuxt-modules/storybook/pull/631.
