### ISSUE TITLE
v7 Migration Instructions

### ISSUE THREAD

**Issue by bmulholland** [nuxt-modules/storybook#452]
I'm upgrading our app to Nuxt 3. How do we migrate to the v7 version? What changes do we need to make?

For example, what's the build-storybook command now? `nuxt storybook build` doesn't work anymore.

**Comment by bmulholland** [comment]
Okay, what? This module doesn't even have storybook as a dependency! OR a peer dependency? So this isn't even about migration... the installation instructions are just wrong, aren't they? https://storybook.nuxtjs.org/getting-started/setup says "that's it!"...

The playground version manually includes a lot of storybook dependencies, do we really need to include all of them?

**Comment by bmulholland** [comment]
I found this really helpful: npx storybook@latest migrate csf-2-to-3

But a lot of other steps are necessary and undocumented. Some are the same as Storybook 7 upgrade, others aren't.

**Comment by CernyMatej** [comment]
Were you able to make it work? I keep getting this error https://github.com/nuxt-modules/storybook/issues/446
(it happens when I'm installing the packages so that's as far as I got)

**Comment by bmulholland** [comment]
I'm much of the way to getting it work, but didn't run into that problem.

Here's the storybook part of my package.json -- which, frankly, is a little silly. Package managers should install all these dependencies for us. That's the whole point.

```
    // Storybook
    "@nuxtjs/storybook": "latest",
    chromatic: "latest",
    "eslint-plugin-storybook": "latest",
    "@storybook/addon-interactions": "latest",
    "@storybook/testing-library": "latest",
    "@storybook/addon-designs": "*",
    // These should all be dependencies of nuxt/storybook...
    "storybook": "latest",
    "@storybook/vue3": "latest",
    "@storybook-vue/nuxt": "latest",
    "@storybook/addon-links": "latest",
    "@storybook/addon-essentials": "latest",
    "@storybook/blocks": "latest",
    "@vue/compiler-core": "latest",
    "react": "latest",
    "react-dom": "latest",
    // These should all be dependencies of @storybook/addon-designs...
    "@storybook/addon-docs": "latest",
    "@storybook/addons": "latest",
    "@storybook/components": "latest",
    "@storybook/manager-api": "latest",
    "@storybook/preview-api": "latest",
    "@storybook/theming": "latest",

    // For interaction testing
    "@storybook/testing-library": "*",
    "@storybook/jest": "*",
    "@storybook/addon-interactions": "*",
```

**Comment by tobiasdiez** [comment]
The dependencies have been improved recently. As for the migration guide to storybook v7 (or now v8), this is available upstream in the storybook docs. I agree it would have been nice to have a v4 > v5+ migration guide for the nuxt module, but I guess now its a bit late for that. Hence closing this now. (But would accept a PR that describes how to migrate from v4).
