### ISSUE TITLE
Support Existing Storybook

### ISSUE THREAD

**Issue by noahgregory-basis** [nuxt-modules/storybook#457]
(initial message)
The function `isStorybookConfigured` [here](https://github.com/nuxt-modules/storybook/blob/5a7d614485fc055b03014d12d67d6fcd9c0fd43d/src/storybook.ts#L130) only checks for `main.ts` if a `tsconfig.json` file exists, when it is still possible for a project with a `tsconfig.json` file to use a `main.js` file (e.g. the project I am currently working on). Please support such configurations.

EDIT: Ok, it appears it just does nothing if Storybook is already installed. Are there plans to support in-place changes to Storybook?

**Comment by tobiasdiez** [comment]
isStorybookConfigured was removed in #592
