### ISSUE TITLE
Static storybook does not pull in nuxt

### ISSUE THREAD

**Issue by filiphazardous** [nuxt-modules/storybook#458]
When I build Storybook statically, I get an error saying `Error: [nuxt] instance unavailable` for components that rely on nuxt (using `<NuxtLink>` being an obvious example).

For a minimal reproduction:

- Pull my fork of nuxt-storybook-module-demo ( https://github.com/filiphazardous/nuxt-storybook-module-demo ) and checkout the `storybook-static` branch.
- `pnpm install`
- `pnpm build-storybook`
- `pnpm static-storybook`
- Visit http://localhost:6007 and click NuxtWelcome > Docs

I can try to fix the problem myself, if someone can give me a pointer

Versions:
- Nuxt: 3.8.2
- Storybook: 7.6.3
- Nuxtjs/storybook: 7.0.0
- Storybook-vue/nuxt: 0.2.0

**Comment by noahgregory-basis** [comment]
Facing this issue as well when using Chromatic, which (to my knowledge) uses static deployments.

**Comment by filiphazardous** [comment]
@chakAs3 Hmm, I just realized I'm not sure if this bug belongs here, or in storybook-vue/nuxt? What do you think?

**Comment by filiphazardous** [comment]
@chakAs3 I've taken some time to dig around, and it seems to me that it is the part that imports the `nuxtApp` in `preview.ts` that fails:
```
const nuxtApp = () => import('#app/entry').then((m) => m.default)
```

For some reason, it seems the typescript alias isn't resolving properly?

**Comment by filiphazardous** [comment]
Even more digging yields these lines in nuxt: https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/templates.ts#L317-L323

When we build storybook statically, `useRuntimeConfig()` returns an empty object. So when we read `.app` on line 321, we get `undefined`. And when we try to dereference `appConfig.baseURL` on line 323, it fails.

I'm not sure how to fix this. Could we inject a runtime config from the storybook addon when we build?

**Comment by filiphazardous** [comment]
Made PR to Nuxt, for something I hope will fix this bug on their end: https://github.com/nuxt/nuxt/pull/24743

**Comment by danielroe** [comment]
I feel like this is a bug in the storybook module.

`window.__NUXT__` is a global variable that is instantiated initially like this:

https://github.com/nuxt/nuxt/blob/b8bfa60ece189c8d806c4c37c622f02794d1d947/packages/nuxt/src/core/runtime/nitro/renderer.ts#L539

... and then later filled in with more information from the page payload.

I think probably the storybook module isn't rendering this script block, which is why this particular issue popped up.

Although this PR might resolve the particular issue, there will be other problems associated with this `__NUXT__` variable not being instantiated in the window and so I think this should be solved in the storybook module.

**Comment by filiphazardous** [comment]
@danielroe Thank you! I will take a look at how to fix this in the right place

**Comment by filiphazardous** [comment]
@danielroe I'm wondering if you could help me with a pointer? This line ( https://github.com/storybook-vue/storybook-nuxt/blob/6d6085b9cb7abcaee75189267b873419f15c614b/packages/storybook-nuxt/src/preview.ts#L9 ) is where the Storybook plugin fails. When it tries to import `#app/entry` the generated `paths.mjs` in the VFS fails (which leads to the reported bug). Isn't Storybook supposed to import `#app/entry`? Or are we supposed to somehow initialize it before we do? Looking through the code in `nuxt/dist/app/entry.js` it looks like Nuxt is getting initialized there, but not being able to import the file creates a Catch 22. (And yes, as you pointed out, my suggested hack in the PR to Nuxt just creates a new error further down the line.) TIA

**Comment by noahgregory-basis** [comment]
I think part of this might be because Nuxt (especially Nuxt 3) doesn't seem to make it easy to deploy statically. I wouldn't be surprised if, somewhere, it's looking for a Nitro server that doesn't exist.

**Comment by filiphazardous** [comment]
@noahgregory-basis I have been stepping through the code over and over, adding console.logs and inspecting, and it doesn't quite look like that - though I'm sure I could be wrong. It just looks like things aren't quite there, which I suppose means that we maybe need to add some dehydrated Nuxt state to the page? I just can't come up with what/how/where

**Comment by noahgregory-basis** [comment]
@filiphazardous Yeah, you've probably looked through it more than me. I'm sorry I'm unable to spend more time looking at it. Here's hoping you can figure it out :)

**Comment by danielroe** [comment]
@filiphazardous Looks like maybe you just need to initialise the `window.__NUXT__` object before importing `#app/entry`.

**Comment by filiphazardous** [comment]
@danielroe Oh, that was the very first thing I did - but then I just got another error. I'll reproduce it and check where that happened

**Comment by danielroe** [comment]
If you need to me to investigate, I can.

Here's what we do in `@nuxt/test-utils`/`nuxt-vitest` in a similar situation:

https://github.com/nuxt/test-utils/blob/74903349e3ee9011ce11355b4c7d06078797e31b/src/environments/vitest/index.ts#L35-L44

**Comment by filiphazardous** [comment]
Digging down in the code, I noticed that this module sets up `__NUXT__` and `import.meta.client` in `preset.ts` ( https://github.com/storybook-vue/storybook-nuxt/blob/path-preview/packages/storybook-nuxt/src/preset.ts#L136-L170 ). In development mode these values are populated by storybook when a file call `env.mjs` is imported, however - this file is not generated i production mode. I guess that would be the root of my problems.

Working around this by adding `window.__NUXT__ = { { config: { app: {} } } }` in `preview.ts` works around the more naïve implementations (like just usig NuxtLink). But for more complex compentents, I run into more trouble.

As I'm currently working on my first Nuxt project, and have hade very limited exposure to Vite before, I don't quite know what to do next. 

Below is a screenshot, showing what "more trouble" looks like.

![Screenshot_2023-12-21_13-20-12](https://github.com/nuxt-modules/storybook/assets/9801577/061e3b54-182b-4451-873b-ffd1a08f35af)

**Comment by daviddomkar** [comment]
Is this fixed? I am still encountering this error. The first load in development has the same problem.

**Comment by alniv94** [comment]
any fix on this?
