### ISSUE TITLE
bug: Storybook installation

### ISSUE THREAD

**Issue by MaciejJezierskiFiskars** [nuxt-modules/storybook#469]
Scenario:

GIVEN I am creating new instance following standard documentation steps to create Nuxt application and how to add storybook:

- https://nuxt.com/docs/getting-started/installation
- https://storybook.nuxtjs.org/getting-started/setup

WHEN I run pnpm dev
THEN I see output about installation which is not interactive

Problem: It looks like application has hanged and nothnig is happening. After some time I have to interrupt the process

<img width="673" alt="Screenshot 2024-01-10 at 10 59 25" src="https://github.com/nuxt-modules/storybook/assets/153720811/3d91abac-e815-4c01-b795-8a70a3a1c29a">

WHEN I run pnpm dev
THEN I have error SB_CORE-COMMON_0003

<img width="1110" alt="Screenshot 2024-01-10 at 11 19 43" src="https://github.com/nuxt-modules/storybook/assets/153720811/19abc7a7-eaf2-4bf8-a66e-3b7520abdd5f">

WHEN I install @storybook-vue/nuxt via pnpm add -D @storybook-vue/nuxt
THEN storybook is running correctly

**Comment by chakAs3** [comment]
@MaciejJezierskiFiskars i don't see what is the issue exactly maybe we need to update the documentation but anyway your Storybook app is working ? let me know if i can close this issue i think it is related to cli i will do some tests

**Comment by maciej-jezierski** [comment]
@chakAs3 there are 2 problems:

1. I think idea of auto adding dependency to package.json is really nice, but output in console is confusing as it's saying: "Which package manager would you like to use?" and then you are not able to choose it, it's automatic. Freezing output is not helping and required second run to see there is actually an error.

2. Not all dependencies which are auto added are fulfilled. @storybook-vue/nuxt is missing. 

I think overall idea is really good, but there are missing parts in documentation which I could only resolve after checking other Issues on GitHub. I tried manual part from documentation and failed too.

After all those steps storybook app is running correctly. My setup

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.8.0
- Builder:          -
- User Config:      devtools, modules, extends, devServer, css, postcss
- Runtime Modules:  @nuxtjs/storybook@^7.0.0
- Build Modules:    -
------------------------------

**Comment by ineshbose** [comment]
> I think idea of auto adding dependency to package.json is really nice

I'm not sure about this personally; a module shouldn't run CLI commands to update `package.json` during `nuxt dev` though. This module seems to run an installer for `@storybook-vue/nuxt`; last working version of this package was v4 (https://github.com/nuxt-modules/storybook/commits/4.x)...

**Comment by maciej-jezierski** [comment]
To be completely honest just having list of dependencies would be enough if CLI is not working correctly.

**Comment by ineshbose** [comment]
> To be completely honest just having list of dependencies would be enough if CLI is not working correctly.

This seems to be one (massive) list - https://github.com/nuxt-modules/storybook/issues/452#issuecomment-1793416641

**Comment by chakAs3** [comment]
> @chakAs3 there are 2 problems:
> 
> 1. I think idea of auto adding dependency to package.json is really nice, but output in console is confusing as it's saying: "Which package manager would you like to use?" and then you are not able to choose it, it's automatic. Freezing output is not helping and required second run to see there is actually an error.
> 2. Not all dependencies which are auto added are fulfilled. @storybook-vue/nuxt is missing.
> 
> I think overall idea is really good, but there are missing parts in documentation which I could only resolve after checking other Issues on GitHub. I tried manual part from documentation and failed too.
> 
> After all those steps storybook app is running correctly. My setup
> 
> * Operating System: Darwin
> * Node Version:     v18.18.2
> * Nuxt Version:     3.9.0
> * CLI Version:      3.10.0
> * Nitro Version:    2.8.1
> * Package Manager:  pnpm@8.8.0
> * Builder:          -
> * User Config:      devtools, modules, extends, devServer, css, postcss
> * Runtime Modules:  @nuxtjs/storybook@^7.0.0
> * Build Modules:    -

i know this part is not yet perfect i did not get time to finish all what i had i mind, however the installation prompt and output is main mixed inspired from nuxi and storybook cli, i tried merge both style i'm not sure to success, the cli is just to automate installation in the existing project however you can manually create you config or use a template from the demo 
https://stackblitz.com/edit/nuxt-starter-cvzvzg?file=package.json

**Comment by chakAs3** [comment]
https://stackblitz.com/edit/nuxt-starter-cvzvzg?embed=1&file=.storybook%2Fpreview.ts

**Comment by schrrobe** [comment]
i am getting the the same error, did you fix the error? @maciej-jezierski 
![image](https://github.com/nuxt-modules/storybook/assets/83832586/076f1ce1-1288-4f52-90cd-1fb9e1595518)

**Comment by MaciejJezierskiFiskars** [comment]
@schrrobe you need to install additional dependency to solve it

pnpm add -D @storybook-vue/nuxt
npm add -D @storybook-vue/nuxt
yarn add -D @storybook-vue/nuxt

**Comment by chakAs3** [comment]
> @schrrobe you need to install additional dependency to solve it
> 
> pnpm add -D @storybook-vue/nuxt npm add -D @storybook-vue/nuxt yarn add -D @storybook-vue/nuxt

actually @storybook-vue/nuxt is the main package to have your Storybook works with Nuxt App, the module is optional, in case you want to run Storybook directly from your Nuxt App. to be honest it is not yet stable i will put more time on it in the future inshallah

**Comment by hungnguyen18** [comment]
> Scenario:
> 
> GIVEN I am creating new instance following standard documentation steps to create Nuxt application and how to add storybook:
> 
> * https://nuxt.com/docs/getting-started/installation
> * https://storybook.nuxtjs.org/getting-started/setup
> 
> WHEN I run pnpm dev THEN I see output about installation which is not interactive
> 
> Problem: It looks like application has hanged and nothnig is happening. After some time I have to interrupt the process
> 
> <img alt="Screenshot 2024-01-10 at 10 59 25" width="673" src="https://private-user-images.githubusercontent.com/153720811/295531714-3d91abac-e815-4c01-b795-8a70a3a1c29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY3NzksIm5iZiI6MTcwOTE3NjQ3OSwicGF0aCI6Ii8xNTM3MjA4MTEvMjk1NTMxNzE0LTNkOTFhYmFjLWU4MTUtNGMwMS1iNzk1LThhNzBhM2ExYzI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwMzE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTg1Y2FkYjI1MjEyYzczMDIyMWQzOGFjMmFhMzdjNGRmYzc3YmFjYjJjNjI3YjlmYzlhYTk5Njc5YmYzODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jOnCGxyUONjb4Skn9RRzwREBhvrl0fbH8PDa4vb0wtk">
> WHEN I run pnpm dev THEN I have error SB_CORE-COMMON_0003
> 
> <img alt="Screenshot 2024-01-10 at 11 19 43" width="1110" src="https://private-user-images.githubusercontent.com/153720811/295531975-19abc7a7-eaf2-4bf8-a66e-3b7520abdd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY3NzksIm5iZiI6MTcwOTE3NjQ3OSwicGF0aCI6Ii8xNTM3MjA4MTEvMjk1NTMxOTc1LTE5YWJjN2E3LWVhZjItNGJmOC1hNjZlLTNiNzUyMGFiZGQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwMzE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjZlMjRjMzMxYzk5NjgxNzI3NTJkZmM2OWI0ZTMzY2RmOGE1MTFiODgxZjAxOWI2MjE2MWVjZThmOWNmZTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w6UvviZyjZzP8yPm6SwwbnBPCmJuo4Mz6gYtzF10v5U">
> WHEN I install @storybook-vue/nuxt via pnpm add -D @storybook-vue/nuxt THEN storybook is running correctly

Same issues
