### ISSUE TITLE
Nuxt hot reloading breaks with nuxt 3.9.x

### ISSUE THREAD

**Issue by niklaswolf** [nuxt-modules/storybook#470]
When using the storybook module with Nuxt 3.9.x, the hot reloading of the nuxt application breaks. Only the hot reloading of storybook works.
Downgrading the app to Nuxt 3.8.x, it works again.
Reading through the release notes of Nuxt (https://github.com/nuxt/nuxt/releases/tag/v3.9.0), I suspect the upgrade from Vite 4 to 5, but this is just a guess.

**Comment by BayBreezy** [comment]
I am not sure if this is the same issue I have but storybok module is running my app in production mode when i run `npm run dev`.

The dev server starts but then storybook module builds the nuxt app for production & then nuxt renders the production build

**Comment by daviddomkar** [comment]
Same issue for me

**Comment by leomav** [comment]
Same issue here

**Comment by yuuzora** [comment]
Same issue here, it makes me unable to correctly work on my project alongside storybook as the hot reloading is too much of a QOL to give it up

**Comment by tobiasdiez** [comment]
Should be fixed by https://github.com/nuxt-modules/storybook/pull/592.

**Comment by g1ronn1mo** [comment]
When trying this with the showcase, located in this repo, I got the same Issue. 

here are the versions: 
```json
{
  "name": "tailwind",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "@pinia/nuxt": "0.5.5",
    "@nuxt/image": "1.8.1",
    "nuxt": "3.13.2",
    "vue": "3.5.11",
    "vue-router": "4.4.5"
  },
  "devDependencies": {
    "@chromatic-com/storybook": "2.0.2",
    "@nuxtjs/storybook": "latest",
    "@storybook/addon-essentials": "8.3.0",
    "@storybook/addon-links": "8.3.0",
    "@storybook/blocks": "8.3.0",
    "@storybook/test": "8.3.0",
    "storybook": "8.3.0"
  }
}
```
