### ISSUE TITLE
nuxt content and story book doesnt play nice

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt-modules/storybook#472]
<img width="994" alt="image" src="https://github.com/nuxt-modules/storybook/assets/93583336/b7f0a257-bec3-4037-b766-330659d929e7">

installing both   modules: [
    "@nuxt/content",
    "@nuxtjs/storybook",
  ],

will break `npm run dev` and result in the above error.  it also breaks` npm run storybook` find reprodction here. https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/tree/nuxt-content-and-story-book-cant-play-nice

**Comment by chakAs3** [comment]
Hi @jpengelbrecht 

Please refer to the demos and the latest version of @storybook-vue/nuxt if you need to have your storybook app working fine.
the module is optional let you have a storybook tab inside you nuxt app

**Comment by jpengelbrecht** [comment]
@chakAs3 I think the problem is story book by itself has very little value as most components work inside the nuxt infrastructure especially if it needs to make use of nuxt content.  

I will play around a bit more and see if I can get it working as not a module but ideally it would be awesome if we can get it working as a module along side nuxt content

**Comment by jpengelbrecht** [comment]
@chakAs3 update,   I tried it again without it being a module.  
<img width="1322" alt="image" src="https://github.com/nuxt-modules/storybook/assets/93583336/64b7b65b-0716-41cd-a90f-1b03e51476fc">
I get this error when running npm run storybook with nuxt content installed.  I also updated the example repo to reflect this

**Comment by chakAs3** [comment]
i have next tried with nuxt content i have to create some demo using @nuxt/content  anyway i will let you know meanwhile can you try the simple demo so you get familar with the implementation and if you have any question, happy to help

**Comment by Vanessi-K** [comment]
Is there any update or progress planned on it. For me it is not possible to use nuxt-content and nuxt-storybook at the same time.

**Comment by jpengelbrecht** [comment]
@Vanessi-K  I actually got tired of waiting so I just started using this lib instead https://histoire.dev/guide/vue3/getting-started.html hope it helps

**Comment by tobiasdiez** [comment]
Let's keep this open if it's still an issue.

**Comment by tobiasdiez** [comment]
@Vanessi-K Could you please provide a reproduction, preferable based on https://github.com/nuxt-modules/storybook/tree/main/examples/starter or https://stackblitz.com/edit/nuxt-modules-storybook-uvf8dh.

**Comment by tobiasdiez** [comment]
I just tried the nightly version of the module in a project that uses nuxt/content and it seems to work well (with limited testing).

Thus, I assume the issue has been resolved in the latest nightly release. For installation instructions, please refer to: https://storybook.nuxtjs.org/getting-started/setup#nightly-builds. If you experience any further problems, don't hesitate to reopen this or create a new issue.
