### ISSUE TITLE
Storybook Module readme is not up to date

### ISSUE THREAD

**Issue by chakAs3** [nuxt-modules/storybook#473]
i noticed that the readme on the website is not up to date with the one the github repo. is there any sync process to run ?
![image](https://github.com/nuxt-modules/storybook/assets/711292/f6cd849c-9093-48c9-9c38-c2dcc4d26107)
![image](https://github.com/nuxt-modules/storybook/assets/711292/a68f2b14-5e2b-4e99-ad62-4ee23034cd73)

**Comment by Atinux** [comment]
It is using the readme from the npm package, does not seem to be this repository for Nuxt 3.
