### ISSUE TITLE
Unable to start nuxt3 storybook project on windows 

### ISSUE THREAD

**Issue by gab9281** [nuxt-modules/storybook#475]
node version : 20.11.0
yarn version : 1.22.21
windows version : 23H2 (22631.3085)

Step to reproduce : 
 - Create nuxt3 repository using `npx nuxi@latest init`
 - Select yarn as package manager
 - add storybook using `yarn add -D @nuxtjs/storybook` 
 - Add nuxt config : 
```
  modules: [
    '@nuxtjs/storybook',
  ],
  storybook: {
    url: 'http://localhost:6006',
    storybookRoute: '/__storybook__',
    port: 6006,
  },
```
 - yarn run dev

Result : 
```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'install' ]
}
```

Try to identify the situation :  
 - Do the same steps but in wsl-ubuntu
 - WORKS !
 - Copy the dependencies : 
```
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "7.6.7",
    "@types/node": "^18.17.5",
    "@storybook/vue3": "7.6.7",
    "@storybook-vue/nuxt": "0.2.1",
    "@nuxtjs/storybook": "7.0.0",
    "@storybook/addon-links": "7.6.7",
    "@storybook/builder-vite": "7.6.7",
    "@storybook/addon-essentials": "7.6.7",
    "@storybook/addon-interactions": "7.6.7",
    "@storybook/testing-library": "^0.2.0",
    "@storybook/blocks": "7.6.7"
```
 - run yarn install

Result : same error 

```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'install' ]
}
```

2nd resolution try : 
 - Upgrade yarn
   - admin console : corepack enable
   - yarn set version stable ( v 4.1.0 )
   - yarn install
   - yarn run dev : Works ...

I've been working a full day on this previously @ job (4 days ago) and had a esbuild-arm error at theses steps.
I am still posting this due to being helpfull for those stuck @ step1 but i'm confused.

While being there : 
The page : https://nuxt.com/modules/storybook have different steps to reproductions and is misleading to another repository : https://github.com/storybook-vue/storybook-nuxt.

Which is the official implementation ?

**Comment by 1337doctor** [comment]
Had the same issue.
It seems that [this line of code](https://github.com/storybook-vue/storybook-nuxt/blob/71b8db7bec25b93338206aee9527e70ac21b4f62/packages/storybook-nuxt-cli/src/init.ts#L93) might cause the problems. ` spawn(cmd, [], { shell: true ... });` setting shell to true might fix this.

**Comment by ilya21743** [comment]
Same problem.
Node v20.11.1
npm v10.4.0
Windows 22H2 (19045.4046)

**Comment by sefacndmr01** [comment]
any updates ?

**Comment by FrankoFM** [comment]
any updates ?

**Comment by AdamovichArtur** [comment]
any updates ?

**Comment by MarlonWiss2212** [comment]
same problem here. any updates?

**Comment by OliverGamborg** [comment]
Also experiencing this error, any workaround or updates?

**Comment by thomscholtens** [comment]
Any updates on this? It is still not working on windows after the last update
