### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Shuriken933** [nuxt-modules/storybook#476]
First of all: there are a lot of repositories about nuxt and storybook...too confusing.

I followed these steps `https://storybook.nuxtjs.org/getting-started/setup` :

1. install storybook `npm install -D @nuxtjs/storybook`
2. add module on nuxt.config.ts `modules: ['@nuxtjs/storybook']`
3. `npm install`
4. `npm run dev`

Now I have my project that works fine and the NuxtDevTool with Storybook tab which remains white. On console i have this:

-----------

Error: Cannot find module 'C:\Users\myuser\IdeaProjects\webLab\node_modules\storybook\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

----------

main.ts and preview.ts are created on .storybook folder.

### main.ts
import type { StorybookConfig } from "@storybook-vue/nuxt";
const config: StorybookConfig = {
  stories: [
    "..\stories/**/*.mdx",
    "..\stories/**/*.stories.@(js|jsx|mjs|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook-vue/nuxt",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
export default config;

### preview.ts
import type { Preview } from "@storybook/vue3";
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};
export default preview;

----------

Is it normal 
`import type { StorybookConfig } from "@storybook-vue/nuxt";`
and
`import type { Preview } from "@storybook/vue3";`

if i don't have these resources on node_modules? On node_modules though Storybook's installation, is created only `@nuxtjs/storybook`

**Comment by memtech3** [comment]
Did you run `npx storybook-nuxt init` after installing storybook?
