### ISSUE TITLE
T[r] is not a function

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt-modules/storybook#477]
i can't preview after build,  demo: https://stackblitz.com/edit/vitejs-vite-snurjg?file=package.json

step:
1.  pnpm run build
2. pnpm run preview
3. you will see the error

i don't know why build is stack on stackblitz, maybe you can donload to local for test
![image](https://github.com/nuxt-modules/storybook/assets/9149999/1f8eae52-bdfc-498b-bbf5-a0406ac55da3)

**Comment by chakAs3** [comment]
hi @baixiaoyu2997 i'm checking all demo and updating them with latest.  i will notify you once it is ready

**Comment by baixiaoyu2997** [comment]
> hi @baixiaoyu2997 i'm checking all demo and updating them with latest. i will notify you once it is ready

Thank you very much for your contribution to storybook and the nuxt community.
storybook 8 is released, I hope this module can support storybook v8 as soon as possible. The current @nuxtjs/storybook experience is very bad, with many bugs and very laggy. When I hot update, the storybook service will also incrementally use the new port number.
I had to temporarily not use the storybook service while developing

**Comment by baixiaoyu2997** [comment]
try with storybook v8 
![image](https://github.com/nuxt-modules/storybook/assets/9149999/710ada33-c0b8-449a-9927-397fbf90581d)

 i got a new error: `Cannot read properties of undefined (reading '_s')`

**Comment by tobiasdiez** [comment]
> try storybook v8 with my private project ![image](https://private-user-images.githubusercontent.com/9149999/321608458-710ada33-c0b8-449a-9927-397fbf90581d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzczNzYsIm5iZiI6MTcxODUzNzA3NiwicGF0aCI6Ii85MTQ5OTk5LzMyMTYwODQ1OC03MTBhZGEzMy1jMGI4LTQ0OWEtOTkyNy0zOTdmYmY5MDU4MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTZUMTEyNDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFiNDEyZDE4Y2M2ODFhYTViNmJmNTRmZWEwN2YxY2YxYWNhZDQyNTU0YzU1MWVjZTc2M2RlYmJhNDc2OTg5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d-iKHe-tqa-Do7W0yB9_gw6Vcd92YwdJ1QgvcqIWbBQ)
> 
> i got a new error: `Cannot read properties of undefined (reading '_s')`

This is most liekely due to pinia. Same error occurs at https://github.com/nuxt-modules/storybook/pull/616. Is this original error still a thing in the most recent version?

**Comment by baixiaoyu2997** [comment]
I am now using mock to handle the store, so I will temporarily close this issue.
