### ISSUE TITLE
Error after install don't find @vitejs/plugin-vue.

### ISSUE THREAD

**Issue by FlorientPlouvin** [nuxt-modules/storybook#509]
Hello, 

Just created a fresh Nuxt 3.11.1 project and immediatly add the storybook module, but I got an error juste after render the page : 
``Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.``. 

I'm on 
``Mac Sonoma 14.1.1``
``Nuxt 3.11.1``
``@nuxtjs/storybook 7.0.``

I use yarn to download package. 

I followed some old tutorials asking me to create a quick config, but I got a warning because I'm not supposed to need it.

**Comment by alniv94** [comment]
got the same error

**Comment by Archetipo95** [comment]
I thing this is linked to this issue: https://github.com/storybookjs/storybook/issues/26306

**Comment by tobiasdiez** [comment]
This should have been fixed by https://github.com/storybook-vue/storybook-nuxt/commit/9d0b108abd37d900607c9d2b31b6c148d5add3a6. If not, please let me know and I'll reopen this issue.
