### ISSUE TITLE
Separate dev and storybook server?

### ISSUE THREAD

**Issue by jimmiejackson414** [nuxt-modules/storybook#555]
Apologies if this has been answered somewhere, but I was unable to find an answer. As a side note, the docs appear to be broken as well so I couldn't find anything there either.

I was wondering if it's possible to run the dev and storybook servers separately? There are times I don't want Storybook to start up, but because this module automatically starts up when running `yarn dev`, for example, I don't have a choice.

**Comment by tobiasdiez** [comment]
Would it be sufficient for your use case to have an option in `nuxt.config.ts` to disable the storybook dev server?

**Comment by jimmiejackson414** [comment]
I'd still like to be able to start the storybook server in a separate terminal window.

For example, one day I work all day on an unrelated bug (so I don't need or want the storybook server), the next day I want to develop a new component, so I run `yarn dev` and `yarn storybook` in separate terminal windows.

Maybe an option in the Nuxt config along the lines of
```typescript
{
  storybook: {
    autoRun: false // defaults to true?
  }
}
```
