### ISSUE TITLE
Publish nightly builds

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-modules/storybook#562]
Todo: configure secret `NPMJS_TOKEN` with the correct deployment token.

**Comment by hp-vev** [comment]
Not sure if this is related but I am having some issues with`TypeError when reading '__STORYBOOK__' property of undefined`. I noticed there is already a fix for that, but it hasn't been released if I am correct?

**Comment by blowsie** [comment]
> Not sure if this is related but I am having some issues with`TypeError when reading '__STORYBOOK__' property of undefined`. I noticed there is already a fix for that, but it hasn't been released if I am correct?

I too have this issue

**Comment by kasperpeulen** [comment]
I can recommend https://github.com/intuit/auto to automate the release process.

**Comment by blowsie** [comment]
The examples are also broken
https://storybook.nuxtjs.org/examples/basic

**Comment by shilman** [comment]
Thanks @tobiasdiez @chakAs3 for being on top of this. 🙏

**Comment by mehcode** [comment]
@chakAs3 @tobiasdiez Can we **please** set this up? I would personally be a lot more motivated to contribute if I could use those contributions quickly without waiting for a formal release.

**Comment by chakAs3** [comment]
@tobiasdiez @mehcode sorry guys,i just payed attention to this notification, it is already done i updated the token

**Comment by tobiasdiez** [comment]
@chakAs3 Thanks a lot! However, it currently fails with
```
npm notice Publishing to https://registry.npmjs.org/ with tag nightly and public access
npm error code EOTP
npm error This operation requires a one-time password from your authenticator.
npm error You can provide a one-time password by passing --otp=<code> to the command you ran.
npm error If you already provided a one-time password then it is likely that you either typoed
npm error it, or it timed out. Please try again.
```

Could you please make sure that you use the "automation" kind of token:
![](https://user-images.githubusercontent.com/4237280/133547460-20788b3e-921c-4a20-8701-c78eec5884db.png)

**Comment by chakAs3** [comment]
it is done 👍 @tobiasdiez

**Comment by tobiasdiez** [comment]
Awesome! This is working now. 🚀
