### ISSUE TITLE
Storybook ^8.0.6 is not working with Tailwind

### ISSUE THREAD

**Issue by prodoxx** [nuxt-modules/storybook#602]
### Description
Current Storybook version in this package is breaking when using it with tailwind. 
You can see the issue as well in the playground: https://storybook.nuxtjs.org/examples/tailwind

There is thread with a fix here: https://github.com/storybookjs/storybook/issues/26869#issuecomment-2130488605. 

Can any of you please update the version with the fix here: https://github.com/nuxt-modules/storybook/blob/30cb7036f1bfc5bc50b11b6b7c3857bcf23886b6/package.json#L81 to use `^8.1.4`  which is the latest version of Storybook: https://github.com/storybookjs/storybook/releases/tag/v8.1.4

**Comment by tobiasdiez** [comment]
Fixed by https://github.com/nuxt-modules/storybook/pull/558.

> You can see the issue as well in the playground: https://storybook.nuxtjs.org/examples/tailwind

What do you mean? How does one see the error there?
