### ISSUE TITLE
Start Storybook independently from nuxt dev

### ISSUE THREAD

**Issue by idmedia-fritscher** [nuxt-modules/storybook#640]
I noticed the module adds a `storybook` script to package.json but storybook also builds when running `nuxt dev`. Is there a way to decouple this so that `nuxt dev` does not start storybook? Thanks

**Comment by JeyP90** [comment]
If you are using version 8.1, they added "enabled" to the storybook-nuxt config.

`storybook: {
    host: 'http://localhost',
    port: 6006,
    enabled: Boolean(process.env.STORYBOOK_ENABLED),
  }`
  
  If not, you could do a workaround:
  
  `modules: [...(process.env.STORYBOOK_ENABLED ? ['@nuxtjs/storybook'] : [])],
  ...(process.env.STORYBOOK_ENABLED ?
    ({
      storybook: {
        url: 'http://localhost:6006',
        port: 6006,
      },
    } as Record<string, unknown>)
  : {}),
  `
