### ISSUE TITLE
Support type extraction with vue-component-meta

### ISSUE THREAD

**Issue by mehcode** [nuxt-modules/storybook#643]
https://storybook.js.org/docs/get-started/vue3-vite#using-vue-component-meta

**Comment by tobiasdiez** [comment]
What exactly are you missing? You can change your config as described in the link if you want to use `vue-component-meta`.

**Comment by mehcode** [comment]
I dug into this one today. This _is_ fixed (and has been for a couple weeks) on `main` with https://github.com/nuxt-modules/storybook/commit/81cb14055f8a93424acce9b1013fc957060fb096 

The part that makes this work for my setup is the move from `plugins.push` to `plugins.unshift`

However the most recent releases of `@nuxtjs/storybook` did not also release `@storybook-vue/nuxt` that includes this fix.

**Comment by mehcode** [comment]
@chakAs3 Can we please get a new release of `@storybook-vue/nuxt` (and another patch release of `@nuxtjs/storybook` to reference it) 🙏

**Comment by tobiasdiez** [comment]
> I dug into this one today. This _is_ fixed (and has been for a couple weeks) on `main` with [81cb140](https://github.com/nuxt-modules/storybook/commit/81cb14055f8a93424acce9b1013fc957060fb096)

Awesome to hear! Thanks for investigating this further.
