### ISSUE TITLE
Error: [nuxt] instance unavailable / Context conflict

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-modules/storybook#661]
With https://github.com/nuxt-modules/storybook/pull/619, composable and other things using the nuxt instance are generally working. However, sometimes when switching between stories one still gets a `[nuxt] instance unavailable` error.

Todo: find a way to reproduce this reliably and investigate what's the problem

Workaround: refresh the page

**Comment by obulat** [comment]
When running the examples using `dev` locally, I can reliably reproduce the context conflict when I navigate to the second story.

The problem is that the module sets `nuxt` to only the current context. However, when installs plugins for the second story's nuxt app, it gets the context using the `nuxtApp._name`, not the `nuxtApp.globalName`. The `_name` is always equal to the `appId`, so it's `nuxt-app` in every story. Thus, when installing plugins for the second story, Nuxt is re-using the first story's context, which causes a context conflict.

I naively fixed this by adding the following in the `packages/storybook-addon/src/preview.ts`:
```
const appId = `nuxt-app`

const nuxtGlobalCtx = getContext(appId)
const currentStoryNuxtAppName = `${appId}-${key}`
const currentStoryNuxtCtx = getContext(currentStoryNuxtAppName)
if (currentStoryNuxtCtx.tryUse()) {
    return
}
```

After `createNuxtApp`:

```
- globalCtx.set(nuxt, true)
+ nuxtGlobalCtx.set(nuxt, true)
```

**Comment by maximilian-schwarz** [comment]
I think this issue is still there. I have create a reproduction. The context conflict only occurs if you create multiple stories.

**Reproduction:**
https://stackblitz.com/edit/nuxt-starter-dz4rbl

If you got to the "SingleStory" docs everything is working fine. You you got to the "MultiStory" docs you can see the context issue.

**Comment by ademyalcin27** [comment]
@tobiasdiez , You closed the issue I opened but the problem still persists.

**Comment by maximilian-schwarz** [comment]
@ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working

**Comment by ademyalcin27** [comment]
> @ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working

Yes I did here, https://github.com/nuxt-modules/storybook/issues/768

**Comment by maximilian-schwarz** [comment]
> > @ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working
> 
> Yes I did here, #768

In your reproduction you use the version 8.2.0. The issue is currently only available with the nightly build. I think the team will include the fix in the next release ;)

to test the fix use the nightly build as dependency.

```
{
  "devDependencies": {
    "@nuxtjs/storybook": "npm:@nuxtjs/storybook@nightly"
  }
}
```

**Comment by ademyalcin27** [comment]
> > > @ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working
> > 
> > 
> > Yes I did here, #768
> 
> In your reproduction you use the version 8.2.0. The issue is currently only available with the nightly build. I think the team will include the fix in the next release ;)
> 
> to test the fix use the nightly build as dependency.
> 
> ```
> {
>   "devDependencies": {
>     "@nuxtjs/storybook": "npm:@nuxtjs/storybook@nightly"
>   }
> }
> ```

I tried this version but still doesn't work autodoc

**Comment by maximilian-schwarz** [comment]
> > > > @ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working
> > > 
> > > 
> > > Yes I did here, #768
> > 
> > 
> > In your reproduction you use the version 8.2.0. The issue is currently only available with the nightly build. I think the team will include the fix in the next release ;)
> > to test the fix use the nightly build as dependency.
> > ```
> > {
> >   "devDependencies": {
> >     "@nuxtjs/storybook": "npm:@nuxtjs/storybook@nightly"
> >   }
> > }
> > ```
> 
> I tried this version but still doesn't work autodoc

You need minimum "nuxt": "3.13.0".

**Comment by ademyalcin27** [comment]
> > > > > @ademyalcin27 can you please create a reproduction? I checked it with the nigthly build and everything is working
> > > > 
> > > > 
> > > > Yes I did here, #768
> > > 
> > > 
> > > In your reproduction you use the version 8.2.0. The issue is currently only available with the nightly build. I think the team will include the fix in the next release ;)
> > > to test the fix use the nightly build as dependency.
> > > ```
> > > {
> > >   "devDependencies": {
> > >     "@nuxtjs/storybook": "npm:@nuxtjs/storybook@nightly"
> > >   }
> > > }
> > > ```
> > 
> > 
> > I tried this version but still doesn't work autodoc
> 
> You need minimum "nuxt": "3.13.0".

Yes its Im using 3.13.0 , but still Im getting same eror

**Comment by tobiasdiez** [comment]
Could you please share an updated reproduction?

**Comment by ademyalcin27** [comment]
> Could you please share an updated reproduction?

https://stackblitz.com/edit/nuxt-starter-ga2at1?file=package.json

**Comment by tobiasdiez** [comment]
"@storybook-vue/nuxt": "^8.2.0",
is not needed and pulls in the older version without the fix

**Comment by ademyalcin27** [comment]
> ```
> "@storybook-vue/nuxt": "^8.2.0",
> ```
> 
> is not needed and pulls in the older version without the fix

Thank you this solve my problem.
