### ISSUE TITLE
Using NuxtLink in story template is not working

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-modules/storybook#666]
The story `NuxtLinkInTemplate` added in https://github.com/nuxt-modules/storybook/pull/618 shows `[Vue warn]: Failed to resolve component: NuxtLink`.

**Comment by sawden** [comment]
This issue still occurs in the current nightly version (8.3.3-28921978.c429594). 
I’ve created a repository to reproduce it: [reproduce-nuxt-storybook-issue-666](https://github.com/sawden/reproduce-nuxt-storybook-issue-666)

![Image](https://github.com/user-attachments/assets/ef35de07-0534-4016-b107-acb79e3db8e0)

**Comment by sawden** [comment]
It has been fixed in pull request [830](https://github.com/nuxt-modules/storybook/pull/830) (version 8.3.3)
Issue can be closed.
