### ISSUE TITLE
When will 0.2.9 appear for „@storybook-vue/nuxt“

### ISSUE THREAD

**Issue by kubilaymelnikov** [nuxt-modules/storybook#667]
Hello @chakAs3, is it foreseeable when you will release the next version with the current corrections of the last few days?

**Comment by tobiasdiez** [comment]
I just cleaned up a few more things and think it would indeed be a good a time for a new release.

@chakAs3 please try the new `pnpm release` which should sync the versions of both packages.

**Comment by chakAs3** [comment]
thank you @tobiasdiez i will do some tests and release new version

**Comment by tobiasdiez** [comment]
Awesome! However, the versions of the nuxt module and the storybook addon are still not aligned.

I guess the problem was that the `pnpm release` script in *the root* was not working. I've fixed it now with https://github.com/nuxt-modules/storybook/pull/683 and https://github.com/nuxt-modules/storybook/pull/681. @chakAs3 could you please give it another try?

**Comment by chakAs3** [comment]
I just released v0.2.10, so it includes your fixes i guess

**Comment by tobiasdiez** [comment]
Thanks, but this only created a new release of the storybook addon, not of the nuxt module. The last release there is a month old: https://www.npmjs.com/package/@nuxtjs/storybook.

 It also recreated the changelog in the  storybook addon package, which I had just deleted. Did you run `pnpm release` from the root?

**Comment by chakAs3** [comment]
@tobiasdiez, I ran the "release," but the build failed. I then tried running it just on the Storybook addon package. I saw your release script, but I'm unable to test it locally, so I'm blindly pushing new releases. Something must have gone wrong 😄.

**Comment by tobiasdiez** [comment]
Can you post the error you are getting?

**Comment by chakAs3** [comment]
No error man awesome, i pushed a release and @nuxtjs/storybook@8.1.2 is published

**Comment by chakAs3** [comment]
@tobiasdie  however no release was created here, but both packages are published 
<img width="663" alt="image" src="https://github.com/nuxt-modules/storybook/assets/711292/c04a4ac8-192d-405f-baf3-ee546d7a4eb5">

**Comment by Vesely** [comment]
Btw there is no README after latest release - https://www.npmjs.com/package/@nuxtjs/storybook?activeTab=readme

**Comment by blowsie** [comment]
Im getting this issue when using 8.1.2
https://github.com/nuxt-modules/storybook/issues/689

**Comment by tobiasdiez** [comment]
> @tobiasdie however no release was created here, but both packages are published

Added tag creation at https://github.com/nuxt-modules/storybook/pull/697. Not sure how the automatic github release is supposed to work.


----

Since the new version has been released, we can close this issue. (#689 already tracks the faulty release)
