### ISSUE TITLE
✘ [ERROR] The entry point "vue" cannot be marked as external

### ISSUE THREAD

**Issue by RobJLeonard** [nuxt-modules/storybook#671]
Hello

I would like to build a component library with nuxt, storybook and shadcn-vue.
However, once I introduce [shadcn-vue](https://www.shadcn-vue.com/docs/installation/nuxt) storybook beings throwing the error: 
✘ [ERROR] The entry point "vue" cannot be marked as external

Here is the repo I have been trying to implement it on
https://github.com/RobJLeonard/z-app

I am primarily a vue2 dev but currently migrating to vue3/nuxt3 and if I can help out solving this issue I would love to help.

Many thanks!

**Comment by tobiasdiez** [comment]
Duplicate of https://github.com/nuxt-modules/storybook/issues/658
