### ISSUE TITLE
Local examples do not build correctly

### ISSUE THREAD

**Issue by obulat** [nuxt-modules/storybook#699]
## Description

Building storybook for examples only renders the sample Nuxt welcome page story and not the stories from the example

## Reproduction

1. Set up the repo dependencies 
- `pnpm install`
- `pnpm example:showcase:build`

2. Build the showcase app: `pnpm example:showcase:storybook:build`
3. Run an http server inside the built directory (I used `npx http-server`).
4. Go to the rendered page, see the error: there are error messages:
```
(0 , n.platform) is not a function
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/react/writing-stories/decorators).
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
TypeError: (0 , n.platform) is not a function
    at http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:22:10645
    at http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:23:486
    at http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:23:512
    at ba (http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:23:515)
    at va (http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:451:37066)
    at http://127.0.0.1:8081/_nuxt/LMqgjtiu.js:451:37161
```

Might be related to `os.platform` in jiti: https://github.com/unjs/jiti/blob/e78daeb2a127d2686b45abe606f39a25efbbf769/src/jiti.ts#L23

**Comment by tobiasdiez** [comment]
For me this is working (now). Which OS do you use?

**Comment by obulat** [comment]
> For me this is working (now). Which OS do you use?

I'm on MacOS.

After the latest PRs, I don't get the `os.platform` errors, and the first component's story looks fine. However, it has warnings in the console:

```
De66xnrA.js:5 [nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'cdnURL')
    at e (BGOWv8qc.js:1:209)
    at b (BGOWv8qc.js:1:174)
    at mt (D8wL0etK.js:7:6272)
    at A (D8wL0etK.js:7:6458)
    at K (D8wL0etK.js:7:6492)
    at D8wL0etK.js:7:19552
    at r (De66xnrA.js:5:25148)
    at Object.runWithContext (CR8tLLMx.js:13:22037)
    at ze (De66xnrA.js:5:25187)
    at De66xnrA.js:5:23338

Caused by: TypeError: Cannot read properties of undefined (reading 'cdnURL')
    at e (BGOWv8qc.js:1:209)
    at b (BGOWv8qc.js:1:174)
    at mt (D8wL0etK.js:7:6272)
    at A (D8wL0etK.js:7:6458)
    at K (D8wL0etK.js:7:6492)
    at D8wL0etK.js:7:19552
    at r (De66xnrA.js:5:25148)
    at Object.runWithContext (CR8tLLMx.js:13:22037)
    at ze (De66xnrA.js:5:25187)
    at De66xnrA.js:5:23338
```

This might be related to the `runtimeConfig` not being set up correctly in the nuxt app, because the error comes from 

https://github.com/nuxt/nuxt/blob/48a8b18083ecfc5b9514d6683a2958e7a1a41e13/packages/nuxt/src/core/templates.ts#L360-L386

Where `cdnURL` should be a property of `appConfig = useRuntimeConfig().app`

The other stories are broken with `context conflict`, which seems to be coming from

https://github.com/unjs/unctx/blob/e587959e9db0820fb4eb3f82a8c83f1dee38ef84/src/index.ts#L39-L49

Can you see the stories after the first one, @tobiasdiez?

**Comment by tobiasdiez** [comment]
The first two errors seem to be harmless, although it would be good to fix them of course.

I do experience the context conflict error or sometimes a nuxt instance error when switching stories, see https://github.com/nuxt-modules/storybook/issues/661. Usually, one just needs to reload the page and then the story shows correctly. Did not yet found the time to investigate this.

Closing as the original is fixed now.
