### ISSUE TITLE
CI actions do not publish packages to npm

### ISSUE THREAD

**Issue by obulat** [nuxt-modules/storybook#716]
## Description

The `release main` action's last several runs [never publish anything](https://github.com/nuxt-modules/storybook/actions/runs/9905226916/job/27364325618) with the following message:
```
Run pnpm publish --recursive --access public --report-summary --no-git-checks
  pnpm publish --recursive --access public --report-summary --no-git-checks
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
There are no new packages that should be published
```

The nightly release in `ci` action [fails](https://github.com/nuxt-modules/storybook/actions/runs/9921422664/job/27409361827) due to error in authentication:

```
npm notice total files: 31
npm notice
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-13T16_44_09_019Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by tobiasdiez** [comment]
Right, this is not used as `pnpm release` takes care of this already. Maybe it would make sense to automatically add a github release upon pushing a tag?

@chakAs3 what would make it easier for you to release a new version?

**Comment by chakAs3** [comment]
@tobiasdiez I used to include GitHub releases in the initial module release script, which is also present in the storybook-addon package.
