### ISSUE TITLE
Nuxt installed with NPM gives missing dependency (@storybook/vue3-vite) for @nuxtjs/storybook

### ISSUE THREAD

**Issue by adalberth** [nuxt-modules/storybook#743]
Hi,

I'm getting a weird error when using nuxt and @nuxtjs/storybook with NPM.

<img width="756" alt="image" src="https://github.com/user-attachments/assets/f45268d7-b9d6-49d2-827f-cd61c7fe3283">

Using Node v20.16.0 and installing nuxt with NPM `npx nuxi@latest init` (Nuxt: 3.12.4) choosing NPM as package manager. Then installing storybook (@nuxtjs/storybook: 8.1.5) with `npx nuxi@latest module add storybook` then running `npx storybook-nuxt init` then running `npm run storybook` gives the error above.

But when installing nuxt with pnpm and choosing pnpm as package manager, it just works.

I'm just following the steps from:
- [https://nuxt.com/docs/getting-started/installation](https://nuxt.com/docs/getting-started/installation)
- [https://storybook.nuxtjs.org/getting-started/setup](https://storybook.nuxtjs.org/getting-started/setup)

**Comment by tobiasdiez** [comment]
Should be fixed by https://github.com/nuxt-modules/storybook/pull/726
