### ISSUE TITLE
The module isnt' working on a fresh Nuxt install

### ISSUE THREAD

**Issue by datsenkoboos** [nuxt-modules/storybook#754]
Hi, i can't get the module to work either with a freshly initialized Nuxt app or with the [example starter](https://github.com/nuxt-modules/storybook/tree/main/examples/starter) from the module repo. Here's what happens on a fresh Nuxt install:

[Repoduction repo](https://github.com/datsenkoboos/nuxt-sb-reprod)

1. Initialize a Nuxt app with `pnpm dlx nuxi@latest init`
2. Run `pnpm dlx nuxi@latest module add storybook`
3. Run `pnpm dev` and get the error: `Storybook needs a "main.js" file`, even though the module docs say:

  > If these files don't exist, the module will automatically generate a basic configuration for them, so you don't have to create these files manually.

4. Run `pnpm dlx storybook-nuxt init`
5. Run `pnpm dev` and get the error:
```
Context conflict                                     nuxt:storybook:build 11:55:25 AM

  at checkConflict (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.a5b1f4d1.mjs:21:13)
  at Object.set (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.a5b1f4d1.mjs:55:9)
  at initNuxt (node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@18.19.44_ioredis@5.4.1_magicast@0.3.4_rollup@4._ksojethl2fpmtynbpdu5jzcccy/node_modules/nuxt/dist/index.mjs:4205:11)
  at Object.ready (node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@18.19.44_ioredis@5.4.1_magicast@0.3.4_rollup@4._ksojethl2fpmtynbpdu5jzcccy/node_modules/nuxt/dist/index.mjs:4107:18)
  at defineNuxtConfig (node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.44_magicast@0.3.4_nuxt@3.12.4_@parcel+watcher@2.4_totxqcalgnom6mrxxrxgiudy2i/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6744:14)
  at async Object.viteFinal (node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.44_magicast@0.3.4_nuxt@3.12.4_@parcel+watcher@2.4_totxqcalgnom6mrxxrxgiudy2i/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6773:22)
  at async createViteServer (node_modules/.pnpm/@storybook+builder-vite@8.0.8_typescript@5.5.4_vite@5.4.0_@types+node@18.19.44_terser@5.31.6_/node_modules/@storybook/builder-vite/dist/index.js:55:11505)
  at async Module.start (node_modules/.pnpm/@storybook+builder-vite@8.0.8_typescript@5.5.4_vite@5.4.0_@types+node@18.19.44_terser@5.31.6_/node_modules/@storybook/builder-vite/dist/index.js:58:1102)
  at async storybookDevServer (node_modules/.pnpm/@storybook+core@8.2.9/node_modules/@storybook/core/dist/core-server/index.js:255880:11)
  at async buildOrThrow (node_modules/.pnpm/@storybook+core@8.2.9/node_modules/@storybook/core/dist/core-server/index.js:255392:12)
```
6. Run `pnpm storybook` and get the error: `The entry point "vue" cannot be marked as external`
7. Remove `@nuxtjs/storybook` from dependencies and update its version in devDependencies from **7.0.2** generated by `storybook-nuxt init` to **8.1.5** (see the [commit](https://github.com/datsenkoboos/nuxt-sb-reprod/commit/0632664b3c4560b4323b317ca808c0424baf02b9))
8. Run `pnpm dev` and get the `Context conflict` error
9. Run `pnpm storybook` and the '`The entry point "vue" cannot be marked as external` error.
10. Bump `@storybook-vue/nuxt` package version to 0.2.8 as stated in [this comment](https://github.com/nuxt-modules/storybook/issues/658#issuecomment-2187921682)
11. Run `pnpm dev` and get the error: `Could not resolve "#app/entry"`
12. Run `pnpm storybook` and get the same error

I'm ready to provide additional info if needed.

**Comment by datsenkoboos** [comment]
**UPD:** Downgrading `nuxt` to **3.11.2** and `@storybook-vue/nuxt` to `0.2.6` gets rid of errors when runnning `pnpm storybook`, but results in the `Context conflict` error when running `pnpm dev`.

**Comment by melvinprindustry** [comment]
We have the same issues and it's extremely frustrating. If you figure out how to get storybook working properly please let me know!

**Comment by marcooop** [comment]
@melvinprindustry The latest fixes seem to solve that problem. Wether you wait till the next release or just use the nightly build in the package.json.

  "devDependencies": {
    ...
    "@nuxtjs/storybook": "npm:@nuxtjs/storybook@nightly",
    ...
}

Solved it for me. Still got some other errors, but i can work. Those may occur through some finesse of the main app.

**Comment by datsenkoboos** [comment]
I've tried using the nightly build, and i'm getting these errors both locally and on CodeSandbox:

![image](https://github.com/user-attachments/assets/eb512d73-b7a7-4adb-9978-43aa4a435653)

[Codesandbox reprod](https://codesandbox.io/p/github/datsenkoboos/nuxt-storybook-nightly/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzwmmpwv000628688pnzklip%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzwmmpwv00022868a1tuibus%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzwmmpwv00042868x0nzrce4%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzwmmpwv00052868ts7x0phd%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzwmmpwv00022868a1tuibus%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzwmmpwv000128685a32hork%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clzwmmpwv00022868a1tuibus%2522%252C%2522activeTabId%2522%253A%2522clzwmmpwv000128685a32hork%2522%257D%252C%2522clzwmmpwv00052868ts7x0phd%2522%253A%257B%2522id%2522%253A%2522clzwmmpwv00052868ts7x0phd%2522%252C%2522activeTabId%2522%253A%2522clzwmn0dd000s2868dcb4a3m4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzwmmrfl000d2868hgkgixm0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clzwmn0dd000s2868dcb4a3m4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzwmmpwv00042868x0nzrce4%2522%253A%257B%2522id%2522%253A%2522clzwmmpwv00042868x0nzrce4%2522%252C%2522activeTabId%2522%253A%2522clzwmmpwv00032868m7odxo2i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzwmmpwv00032868m7odxo2i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522NEW_TERMINAL%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzwmmuk7000k2868f08iop8v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D); [Repo](https://github.com/datsenkoboos/nuxt-storybook-nightly)

@marcooop @tobiasdiez What am i missing?

**Comment by tobiasdiez** [comment]
Remove the dependency `"@storybook-vue/nuxt": "^8.1.5",`

**Comment by datsenkoboos** [comment]
Thank you! The errors have been resolved. But my component isn't being rendered in the Storybook preview, it fails with this error:

![image](https://github.com/user-attachments/assets/07867f78-2d7f-46df-892a-0e7faed71914)

Warnings are still present in the terminal:

![image](https://github.com/user-attachments/assets/7d664800-1703-4be2-aaa3-0e7b567e7142)

What could be the issue?

**Comment by maximilian-schwarz** [comment]
@datsenkoboos Got the same error message like you :(

**Comment by tobiasdiez** [comment]
Try setting https://nuxt.com/docs/api/nuxt-config#runtime compiler to true.

**Comment by maximilian-schwarz** [comment]
If you set the runtimeCompiler to `true` the [Vue warn] is gone.

But the two warnings are still there:
```js
 WARN  Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files                                                                                                                                                                                                                                                                               15:22:57
 WARN  Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files 
```

**Comment by tobiasdiez** [comment]
These warnings are an issue with the upstream storybook packages (also appear in a pure vue-setting without nuxt).
