### ISSUE TITLE
@nuxtjs/storybook failed to intialize

### ISSUE THREAD

**Issue by Besufikad17** [nuxt-modules/storybook#771]
I have followed steps listed in the readme file to install and intialize storybook in my nuxt3 project but I am getting `error Invariant Violation: expected hoisted manifest for "@storybook-vue/nuxt#vue#@vue/server-renderer#@vue/compiler-ssr"` error when I run `npx storybook-nuxt init`. Am I missing somthing? Thanks in advance

**Comment by tobiasdiez** [comment]
Could you please fill out the bug report issue template; and in particular provide a reproduction. Thanks!
