### ISSUE TITLE
Setup doesn't work

### ISSUE THREAD

**Issue by luca-smartpricing** [nuxt-modules/storybook#793]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yo3hjv

### Describe the bug

In the docs you say:
Installation:
Install @nuxtjs/storybook dependency to your project:
`npx nuxi@latest module add storybook`
Add it to your modules section in your nuxt.config:
```
export default defineNuxtConfig({
  modules: ['@nuxtjs/storybook'],
})
```
That's it! You can now use Storybook in your Nuxt app ✨

**It's not true. It doesnt'work**

### Error
```
ERROR  No configuration files have been found in your configDir: /Users/lucabortolussi/Projects/website-v3/.storybook.                       nuxt:storybook:build 12:28:45 PM
Storybook needs a "main.js" file, please add it.

You can pass a --config-dir flag to tell Storybook, where your main.js file is located at.

More info: https://storybook.js.org/docs/configure


  Storybook needs a "main.js" file, please add it.
  
  You can pass a --config-dir flag to tell Storybook, where your main.js file is located at.
  
  More info: https://storybook.js.org/docs/configure
  
  at validateConfigurationFiles (node_modules/@storybook/core/dist/common/index.js:139226:11)
  at async loadMainConfig (node_modules/@storybook/core/dist/common/index.js:140361:3)
  at async buildDevStandalone (node_modules/@storybook/core/dist/core-server/index.js:48532:11)
  at async withTelemetry (node_modules/@storybook/core/dist/core-server/index.js:47133:12)
  at async setupStorybook (node_modules/@nuxtjs/storybook/dist/module.mjs:54:18)

 WARN Broken build, fix the error above.
You may need to refresh the browser.

ERROR  [unhandledRejection] No configuration files have been found in your configDir: /Users/lucabortolussi/Projects/website-v3/.storybook.
Storybook needs a "main.js" file, please add it.

You can pass a --config-dir flag to tell Storybook, where your main.js file is located at.

More info: https://storybook.js.org/docs/configure

Storybook needs a "main.js" file, please add it.

You can pass a --config-dir flag to tell Storybook, where your main.js file is located at.

More info: https://storybook.js.org/docs/configure at validateConfigurationFiles (node_modules/@storybook/core/dist/common/index.js:139226:11)
```

**Comment by tobiasdiez** [comment]
Right, you also need to add the config of https://storybook.nuxtjs.org/storybook/config#default-configuration. 
That page is also wrong - we would like to ship a default config but this is not yet done (will be part of https://github.com/nuxt-modules/storybook/pull/660 and/or https://github.com/nuxt-modules/storybook/pull/659).

In the meantime, could you please create a PR that brings the docs from a wishful thinking more in line with reality? Thanks!
