### ISSUE TITLE
How to change .storybook path?

### ISSUE THREAD

**Issue by kogratte** [nuxt-modules/storybook#810]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

N/A

### Additional context

I'm trying to make this module work on a common package we're using. I would like to change the .storybook directory in order to avoid this kind of error: 
`No configuration files have been found in your configDir: /Users/nico/sources/BEST_PROJECT_EVER/.playground/.storybook`

Indeed. I would like to use the one on project root's directory.

I cannot find anything on the documentation nor issues, and I'm not even sure this can be done as of today. 

Any tips?

**Comment by tobiasdiez** [comment]
I don't think this can be done, and in either case this would be a feature requests upstream in the main storybook repo.

(You can always add a symlink that points to the parent `.storybook` folder.)
