### ISSUE TITLE
Project is in a non-functional state. Please fix or update docs.

### ISSUE THREAD

**Issue by juni0r** [nuxt-modules/storybook#811]
### Environment

nuxt@3.15.0
@nuxtjs/storybook@8.3.2

### Reproduction

Create a fresh nuxt project and add the module as per documentation. Run storybook task.

### Describe the bug

I tried to install storybook-nuxt in a fresh Nuxt project and it's not working. I followed the steps outlined in the docs, namely:

```bash
npx nuxi@latest module add storybook
npx storybook-nuxt init
npm run storybook
```

This won't work due to a missing package `@storybook/vue3-vite`...

```bash
npm i -D @storybook/vue3-vite@8.0.8
```
results in
```bash
Error: Build failed with 1 error:
error: The entry point "vue" cannot be marked as external
```

Subsequent attempts to update packages and fixing mismatched peer dependencies will just result in cascades of incompatibilities and utlimate failure.

### Additional context

Reading through various issues it appears that there's currently no clearly documented way to install the module and its dependencies in a working state. If you're unable to fix it it would be very much appreciated if you could at least update the documentation and add a warning that the project is in a non-functional state. It would have saved me a few hours trying to get it to work.

Thank you!

**Comment by lafllamme** [comment]
@bwaltz @juni0r 

You can have a look inside here at a correct package.json (afaik)

https://github.com/nuxt-modules/storybook/issues/776

**Comment by tobiasdiez** [comment]
https://github.com/nuxt-modules/storybook/issues/813
